//
// AlertRulesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AlertRulesAPI {

    /**
     Create alert rule

     - parameter createAlertRuleRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateAlertRule201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createAlertRule(createAlertRuleRequest: CreateAlertRuleRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateAlertRule201Response {
        return try await createAlertRuleWithRequestBuilder(createAlertRuleRequest: createAlertRuleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create alert rule
     - POST /v1/alert-rules
     - parameter createAlertRuleRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateAlertRule201Response>
     */
    open class func createAlertRuleWithRequestBuilder(createAlertRuleRequest: CreateAlertRuleRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateAlertRule201Response> {
        let localVariablePath = "/v1/alert-rules"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createAlertRuleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateAlertRule201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get alert rule

     - parameter ruleId: (path) Alert rule ID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateAlertRule201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAlertRule(ruleId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateAlertRule201Response {
        return try await getAlertRuleWithRequestBuilder(ruleId: ruleId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get alert rule
     - GET /v1/alert-rules/{rule_id}
     - parameter ruleId: (path) Alert rule ID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateAlertRule201Response>
     */
    open class func getAlertRuleWithRequestBuilder(ruleId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateAlertRule201Response> {
        var localVariablePath = "/v1/alert-rules/{rule_id}"
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rule_id}", with: ruleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateAlertRule201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update alert rule

     - parameter ruleId: (path) Alert rule ID
     - parameter updateAlertRuleRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateAlertRule201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateAlertRule(ruleId: String, updateAlertRuleRequest: UpdateAlertRuleRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateAlertRule201Response {
        return try await updateAlertRuleWithRequestBuilder(ruleId: ruleId, updateAlertRuleRequest: updateAlertRuleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update alert rule
     - PUT /v1/alert-rules/{rule_id}
     - parameter ruleId: (path) Alert rule ID
     - parameter updateAlertRuleRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateAlertRule201Response>
     */
    open class func updateAlertRuleWithRequestBuilder(ruleId: String, updateAlertRuleRequest: UpdateAlertRuleRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateAlertRule201Response> {
        var localVariablePath = "/v1/alert-rules/{rule_id}"
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rule_id}", with: ruleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateAlertRuleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateAlertRule201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List alert rules

     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListAlertRules200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listAlertRules(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> ListAlertRules200Response {
        return try await listAlertRulesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List alert rules
     - GET /v1/alert-rules
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListAlertRules200Response>
     */
    open class func listAlertRulesWithRequestBuilder(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<ListAlertRules200Response> {
        let localVariablePath = "/v1/alert-rules"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListAlertRules200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete alert rule

     - parameter ruleId: (path) Alert rule ID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeletePolicyRule200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteAlertRule(ruleId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> DeletePolicyRule200Response {
        return try await deleteAlertRuleWithRequestBuilder(ruleId: ruleId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete alert rule
     - DELETE /v1/alert-rules/{rule_id}
     - parameter ruleId: (path) Alert rule ID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeletePolicyRule200Response>
     */
    open class func deleteAlertRuleWithRequestBuilder(ruleId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/alert-rules/{rule_id}"
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rule_id}", with: ruleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
