//
// ContactListsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ContactListsAPI {

    /**
     Append to contact list
     
     - parameter listId: (path) Contact list UUID 
     - parameter appendToContactListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AppendToContactList200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func appendToContactList(listId: String, appendToContactListRequest: AppendToContactListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> AppendToContactList200Response {
        return try await appendToContactListWithRequestBuilder(listId: listId, appendToContactListRequest: appendToContactListRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Append to contact list
     - POST /v1/contact-lists/{list_id}/append
     - Append validated emails from additional jobs to an existing contact list. Duplicates are automatically skipped.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) Contact list UUID 
     - parameter appendToContactListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AppendToContactList200Response> 
     */
    open class func appendToContactListWithRequestBuilder(listId: String, appendToContactListRequest: AppendToContactListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<AppendToContactList200Response> {
        var localVariablePath = "/v1/contact-lists/{list_id}/append"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appendToContactListRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppendToContactList200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create contact list
     
     - parameter createContactListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateContactList201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createContactList(createContactListRequest: CreateContactListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateContactList201Response {
        return try await createContactListWithRequestBuilder(createContactListRequest: createContactListRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create contact list
     - POST /v1/contact-lists
     - Create a new contact list from one or more completed validation jobs. Only accepted (valid) emails are included.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createContactListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateContactList201Response> 
     */
    open class func createContactListWithRequestBuilder(createContactListRequest: CreateContactListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateContactList201Response> {
        let localVariablePath = "/v1/contact-lists"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createContactListRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateContactList201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get inactive contacts report
     
     - parameter days: (query) Inactivity threshold in days (optional, default to 90)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetInactiveContactsReport200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getInactiveContactsReport(days: Int? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> GetInactiveContactsReport200Response {
        return try await getInactiveContactsReportWithRequestBuilder(days: days, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get inactive contacts report
     - GET /v1/contacts/inactive-report
     - Get a report of contacts across all lists with no engagement activity (opens, clicks) in the specified period.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter days: (query) Inactivity threshold in days (optional, default to 90)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetInactiveContactsReport200Response> 
     */
    open class func getInactiveContactsReportWithRequestBuilder(days: Int? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<GetInactiveContactsReport200Response> {
        let localVariablePath = "/v1/contacts/inactive-report"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "days": (wrappedValue: days?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetInactiveContactsReport200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List contact lists
     
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListContactLists200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listContactLists(page: Int? = nil, perPage: Int? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> ListContactLists200Response {
        return try await listContactListsWithRequestBuilder(page: page, perPage: perPage, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List contact lists
     - GET /v1/contact-lists
     - List contact lists for the authenticated account. Contact lists are built from validated email jobs.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListContactLists200Response> 
     */
    open class func listContactListsWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<ListContactLists200Response> {
        let localVariablePath = "/v1/contact-lists"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListContactLists200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Query contact list
     
     - parameter listId: (path) Contact list UUID 
     - parameter queryContactListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: QueryContactList200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func queryContactList(listId: String, queryContactListRequest: QueryContactListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> QueryContactList200Response {
        return try await queryContactListWithRequestBuilder(listId: listId, queryContactListRequest: queryContactListRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Query contact list
     - POST /v1/contact-lists/{list_id}/query
     - Query contact list entries with structured filters. Supports filtering by validation status, domain, and other attributes.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) Contact list UUID 
     - parameter queryContactListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<QueryContactList200Response> 
     */
    open class func queryContactListWithRequestBuilder(listId: String, queryContactListRequest: QueryContactListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<QueryContactList200Response> {
        var localVariablePath = "/v1/contact-lists/{list_id}/query"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: queryContactListRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QueryContactList200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
