//
// EmailSendingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class EmailSendingAPI {

    /**
     Send to multiple recipients (max 100)
     
     - parameter batchDeliverRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BatchDeliverResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deliverBatch(batchDeliverRequest: BatchDeliverRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> BatchDeliverResponse {
        return try await deliverBatchWithRequestBuilder(batchDeliverRequest: batchDeliverRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Send to multiple recipients (max 100)
     - POST /v1/deliver/batch
     - Send a single message to up to 100 recipients. Shares the same message body across all recipients. Each recipient is processed independently.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter batchDeliverRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BatchDeliverResponse> 
     */
    open class func deliverBatchWithRequestBuilder(batchDeliverRequest: BatchDeliverRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<BatchDeliverResponse> {
        let localVariablePath = "/v1/deliver/batch"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: batchDeliverRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BatchDeliverResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Send a single email
     
     - parameter deliverRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeliverResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deliverEmail(deliverRequest: DeliverRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> DeliverResponse {
        return try await deliverEmailWithRequestBuilder(deliverRequest: deliverRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Send a single email
     - POST /v1/deliver
     - Send a transactional email through the safety pipeline. Validates recipients, checks domain ownership, and queues for delivery. Requires a verified sending domain.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter deliverRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeliverResponse> 
     */
    open class func deliverEmailWithRequestBuilder(deliverRequest: DeliverRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<DeliverResponse> {
        let localVariablePath = "/v1/deliver"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deliverRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeliverResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
