//
// EventsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class EventsAPI {

    /**
     Track a commerce event

     - parameter trackEventRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TrackEventResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func trackEvent(trackEventRequest: TrackEventRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> TrackEventResponse {
        return try await trackEventWithRequestBuilder(trackEventRequest: trackEventRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Track a commerce event
     - POST /v1/events/track
     - Ingest a commerce event (purchase, cart abandonment, browse, wishlist, review, etc.). Supports idempotency via the idempotency_key field (5 minute Redis TTL + DB unique constraint).
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter trackEventRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TrackEventResponse>
     */
    open class func trackEventWithRequestBuilder(trackEventRequest: TrackEventRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<TrackEventResponse> {
        let localVariablePath = "/v1/events/track"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: trackEventRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TrackEventResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
