//
// MessageEventsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MessageEventsAPI {

    /**
     Get message events
     
     - parameter messageId: (query) UUID of the sent message 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetMessageEvents200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMessageEvents(messageId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> GetMessageEvents200Response {
        return try await getMessageEventsWithRequestBuilder(messageId: messageId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get message events
     - GET /v1/message-events
     - Get delivery and engagement events for a specific sent message. Returns events in chronological order with bot detection.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter messageId: (query) UUID of the sent message 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetMessageEvents200Response> 
     */
    open class func getMessageEventsWithRequestBuilder(messageId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<GetMessageEvents200Response> {
        let localVariablePath = "/v1/message-events"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "message_id": (wrappedValue: messageId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetMessageEvents200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
