//
// OAuth20API.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class OAuth20API {

    /**
     * enum for parameter grantType
     */
    public enum GrantType_createToken: String, CaseIterable, Sendable {
        case authorizationCode = "authorization_code"
        case clientCredentials = "client_credentials"
        case refreshToken = "refresh_token"
    }

    /**
     Create token

     - parameter grantType: (form)
     - parameter code: (form) Authorization code (for authorization_code grant) (optional)
     - parameter redirectUri: (form) Must match the original redirect_uri (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter refreshToken: (form) Refresh token (for refresh_token grant) (optional)
     - parameter scope: (form) Space-separated scopes (optional)
     - parameter codeVerifier: (form) PKCE code verifier (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateToken200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createToken(grantType: GrantType_createToken, code: String? = nil, redirectUri: String? = nil, clientId: String? = nil, clientSecret: String? = nil, refreshToken: String? = nil, scope: String? = nil, codeVerifier: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateToken200Response {
        return try await createTokenWithRequestBuilder(grantType: grantType, code: code, redirectUri: redirectUri, clientId: clientId, clientSecret: clientSecret, refreshToken: refreshToken, scope: scope, codeVerifier: codeVerifier, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create token
     - POST /oauth/token
     - Exchange an authorization code, client credentials, or refresh token for access and refresh tokens. Authenticate via client_secret_post or client_secret_basic.
     - parameter grantType: (form)
     - parameter code: (form) Authorization code (for authorization_code grant) (optional)
     - parameter redirectUri: (form) Must match the original redirect_uri (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter refreshToken: (form) Refresh token (for refresh_token grant) (optional)
     - parameter scope: (form) Space-separated scopes (optional)
     - parameter codeVerifier: (form) PKCE code verifier (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateToken200Response>
     */
    open class func createTokenWithRequestBuilder(grantType: GrantType_createToken, code: String? = nil, redirectUri: String? = nil, clientId: String? = nil, clientSecret: String? = nil, refreshToken: String? = nil, scope: String? = nil, codeVerifier: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateToken200Response> {
        let localVariablePath = "/oauth/token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "grant_type": grantType.rawValue,
            "code": code,
            "redirect_uri": redirectUri,
            "client_id": clientId,
            "client_secret": clientSecret,
            "refresh_token": refreshToken,
            "scope": scope,
            "code_verifier": codeVerifier,
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateToken200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get JSON Web Key Set

     - parameter apiConfiguration: The configuration for the http request.
     - returns: JwksResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getJwks(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> JwksResponse {
        return try await getJwksWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get JSON Web Key Set
     - GET /.well-known/jwks.json
     - Public key set for verifying JWT access tokens issued by this server.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JwksResponse>
     */
    open class func getJwksWithRequestBuilder(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<JwksResponse> {
        let localVariablePath = "/.well-known/jwks.json"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JwksResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter tokenTypeHint
     */
    public enum TokenTypeHint_introspectToken: String, CaseIterable, Sendable {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
    }

    /**
     Introspect token

     - parameter token: (form) Token to introspect
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: IntrospectToken200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func introspectToken(token: String, tokenTypeHint: TokenTypeHint_introspectToken? = nil, clientId: String? = nil, clientSecret: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> IntrospectToken200Response {
        return try await introspectTokenWithRequestBuilder(token: token, tokenTypeHint: tokenTypeHint, clientId: clientId, clientSecret: clientSecret, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Introspect token
     - POST /oauth/introspect
     - Introspect a token to determine its active state and metadata (RFC 7662). Requires client authentication.
     - parameter token: (form) Token to introspect
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<IntrospectToken200Response>
     */
    open class func introspectTokenWithRequestBuilder(token: String, tokenTypeHint: TokenTypeHint_introspectToken? = nil, clientId: String? = nil, clientSecret: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<IntrospectToken200Response> {
        let localVariablePath = "/oauth/introspect"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "token": token,
            "token_type_hint": tokenTypeHint?.rawValue,
            "client_id": clientId,
            "client_secret": clientSecret,
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntrospectToken200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     OAuth server metadata

     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuthServerMetadata
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func oauthServerMetadata(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> OAuthServerMetadata {
        return try await oauthServerMetadataWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     OAuth server metadata
     - GET /.well-known/oauth-authorization-server
     - OAuth 2.0 Authorization Server Metadata (RFC 8414). Returns server configuration including supported grant types, scopes, and endpoints.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuthServerMetadata>
     */
    open class func oauthServerMetadataWithRequestBuilder(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<OAuthServerMetadata> {
        let localVariablePath = "/.well-known/oauth-authorization-server"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuthServerMetadata>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter tokenTypeHint
     */
    public enum TokenTypeHint_revokeToken: String, CaseIterable, Sendable {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
    }

    /**
     Revoke token

     - parameter token: (form) Token to revoke
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func revokeToken(token: String, tokenTypeHint: TokenTypeHint_revokeToken? = nil, clientId: String? = nil, clientSecret: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) {
        _ = try await revokeTokenWithRequestBuilder(token: token, tokenTypeHint: tokenTypeHint, clientId: clientId, clientSecret: clientSecret, apiConfiguration: apiConfiguration).execute()
    }

    /**
     Revoke token
     - POST /oauth/revoke
     - Revoke an access or refresh token (RFC 7009). Requires client authentication. Always returns 200 per spec to prevent token scanning.
     - parameter token: (form) Token to revoke
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void>
     */
    open class func revokeTokenWithRequestBuilder(token: String, tokenTypeHint: TokenTypeHint_revokeToken? = nil, clientId: String? = nil, clientSecret: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/revoke"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "token": token,
            "token_type_hint": tokenTypeHint?.rawValue,
            "client_id": clientId,
            "client_secret": clientSecret,
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
