//
// SenderHealthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SenderHealthAPI {

    /**
     * enum for parameter period
     */
    public enum Period_getSenderHealth: String, Sendable, CaseIterable {
        case _7d = "7d"
        case _30d = "30d"
        case _90d = "90d"
    }

    /**
     Get sender health score
     
     - parameter period: (query) Time period for health calculation (optional, default to ._30d)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetSenderHealth200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSenderHealth(period: Period_getSenderHealth? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> GetSenderHealth200Response {
        return try await getSenderHealthWithRequestBuilder(period: period, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get sender health score
     - GET /v1/sender-health
     - Get an aggregate sender health score (0-100) across all sending domains. Factors in delivery rate, bounce rate, complaint rate, and authentication status.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter period: (query) Time period for health calculation (optional, default to ._30d)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetSenderHealth200Response> 
     */
    open class func getSenderHealthWithRequestBuilder(period: Period_getSenderHealth? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<GetSenderHealth200Response> {
        let localVariablePath = "/v1/sender-health"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "period": (wrappedValue: period?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSenderHealth200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter period
     */
    public enum Period_getSenderHealthTrend: String, Sendable, CaseIterable {
        case _7d = "7d"
        case _30d = "30d"
        case _90d = "90d"
    }

    /**
     Get sender health trend
     
     - parameter period: (query) Time period for trend data (optional, default to ._30d)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetSenderHealthTrend200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSenderHealthTrend(period: Period_getSenderHealthTrend? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> GetSenderHealthTrend200Response {
        return try await getSenderHealthTrendWithRequestBuilder(period: period, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get sender health trend
     - GET /v1/sender-health/trend
     - Get historical sender health scores over time for trend analysis. Returns daily data points for the requested period.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter period: (query) Time period for trend data (optional, default to ._30d)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetSenderHealthTrend200Response> 
     */
    open class func getSenderHealthTrendWithRequestBuilder(period: Period_getSenderHealthTrend? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<GetSenderHealthTrend200Response> {
        let localVariablePath = "/v1/sender-health/trend"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "period": (wrappedValue: period?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSenderHealthTrend200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
