//
// StoreConnectionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class StoreConnectionsAPI {

    /**
     Create a store connection

     - parameter createStoreRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateStore201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createStore(createStoreRequest: CreateStoreRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateStore201Response {
        return try await createStoreWithRequestBuilder(createStoreRequest: createStoreRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a store connection
     - POST /v1/stores
     - Connect an e-commerce store (WooCommerce, PrestaShop, Shopify, or product feed). After creation, trigger a sync to import products.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createStoreRequest: (body)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateStore201Response>
     */
    open class func createStoreWithRequestBuilder(createStoreRequest: CreateStoreRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateStore201Response> {
        let localVariablePath = "/v1/stores"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createStoreRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateStore201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Disconnect a store

     - parameter storeId: (path) Store connection UUID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DisconnectStore200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func disconnectStore(storeId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> DisconnectStore200Response {
        return try await disconnectStoreWithRequestBuilder(storeId: storeId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Disconnect a store
     - DELETE /v1/stores/{store_id}
     - Disconnect a store and deactivate its products. Products are retained but marked inactive.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DisconnectStore200Response>
     */
    open class func disconnectStoreWithRequestBuilder(storeId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<DisconnectStore200Response> {
        var localVariablePath = "/v1/stores/{store_id}"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisconnectStore200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a store connection

     - parameter storeId: (path) Store connection UUID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateStore201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getStore(storeId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateStore201Response {
        return try await getStoreWithRequestBuilder(storeId: storeId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a store connection
     - GET /v1/stores/{store_id}
     - Get details of a specific store connection including sync status and product count.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateStore201Response>
     */
    open class func getStoreWithRequestBuilder(storeId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateStore201Response> {
        var localVariablePath = "/v1/stores/{store_id}"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateStore201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List store connections

     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListStores200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listStores(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> ListStores200Response {
        return try await listStoresWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List store connections
     - GET /v1/stores
     - List all store connections for the authenticated account.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListStores200Response>
     */
    open class func listStoresWithRequestBuilder(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<ListStores200Response> {
        let localVariablePath = "/v1/stores"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListStores200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Trigger product sync

     - parameter storeId: (path) Store connection UUID
     - parameter idempotencyKey: (header) Idempotency key to prevent duplicate syncs (5 min TTL) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SyncResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func triggerSync(storeId: String, idempotencyKey: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> SyncResponse {
        return try await triggerSyncWithRequestBuilder(storeId: storeId, idempotencyKey: idempotencyKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Trigger product sync
     - POST /v1/stores/{store_id}/sync
     - Trigger a manual product sync for a store. Supports idempotency via the Idempotency-Key header (5 minute TTL).
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID
     - parameter idempotencyKey: (header) Idempotency key to prevent duplicate syncs (5 min TTL) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SyncResponse>
     */
    open class func triggerSyncWithRequestBuilder(storeId: String, idempotencyKey: String? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<SyncResponse> {
        var localVariablePath = "/v1/stores/{store_id}/sync"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Idempotency-Key": idempotencyKey,
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SyncResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
