//
// SubscriberListsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SubscriberListsAPI {

    /**
     Confirm subscription
     
     - parameter token: (path) Confirmation token from email 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ConfirmSubscription200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func confirmSubscription(token: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> ConfirmSubscription200Response {
        return try await confirmSubscriptionWithRequestBuilder(token: token, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Confirm subscription
     - GET /v1/confirm/{token}
     - Confirm a pending subscription via the token sent in the confirmation email. No authentication required. Redirects to the list's configured redirect URL if set, otherwise returns JSON. Tokens expire after 72 hours.
     - parameter token: (path) Confirmation token from email 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ConfirmSubscription200Response> 
     */
    open class func confirmSubscriptionWithRequestBuilder(token: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<ConfirmSubscription200Response> {
        var localVariablePath = "/v1/confirm/{token}"
        let tokenPreEscape = "\(APIHelper.mapValueToPathItem(token))"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConfirmSubscription200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Create a subscriber list
     
     - parameter createListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateList201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createList(createListRequest: CreateListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateList201Response {
        return try await createListWithRequestBuilder(createListRequest: createListRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a subscriber list
     - POST /v1/lists
     - Create a new subscriber list. Use lists to organize subscribers and manage double opt-in confirmation flows.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createListRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateList201Response> 
     */
    open class func createListWithRequestBuilder(createListRequest: CreateListRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateList201Response> {
        let localVariablePath = "/v1/lists"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createListRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateList201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a subscriber list
     
     - parameter listId: (path) List UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeletePolicyRule200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteList(listId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> DeletePolicyRule200Response {
        return try await deleteListWithRequestBuilder(listId: listId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a subscriber list
     - DELETE /v1/lists/{list_id}
     - Soft-delete a subscriber list. Existing subscribers are retained but the list is no longer usable.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) List UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeletePolicyRule200Response> 
     */
    open class func deleteListWithRequestBuilder(listId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/lists/{list_id}"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a subscriber list
     
     - parameter listId: (path) List UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateList201Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getList(listId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> CreateList201Response {
        return try await getListWithRequestBuilder(listId: listId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a subscriber list
     - GET /v1/lists/{list_id}
     - Get details of a specific subscriber list including subscriber and confirmed counts.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) List UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateList201Response> 
     */
    open class func getListWithRequestBuilder(listId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<CreateList201Response> {
        var localVariablePath = "/v1/lists/{list_id}"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateList201Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List subscriber lists
     
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 25)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetLists200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLists(page: Int? = nil, perPage: Int? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> GetLists200Response {
        return try await getListsWithRequestBuilder(page: page, perPage: perPage, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List subscriber lists
     - GET /v1/lists
     - List all subscriber lists for the authenticated account with pagination.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 25)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetLists200Response> 
     */
    open class func getListsWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<GetLists200Response> {
        let localVariablePath = "/v1/lists"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetLists200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter status
     */
    public enum Status_getSubscribers: String, Sendable, CaseIterable {
        case pending = "pending"
        case confirmed = "confirmed"
        case unsubscribed = "unsubscribed"
        case bounced = "bounced"
    }

    /**
     List subscribers
     
     - parameter listId: (path) List UUID 
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 50)
     - parameter status: (query) Filter by subscriber status (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetSubscribers200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSubscribers(listId: String, page: Int? = nil, perPage: Int? = nil, status: Status_getSubscribers? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> GetSubscribers200Response {
        return try await getSubscribersWithRequestBuilder(listId: listId, page: page, perPage: perPage, status: status, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List subscribers
     - GET /v1/lists/{list_id}/subscribers
     - List paginated subscribers for a specific list. Optionally filter by status.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) List UUID 
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 50)
     - parameter status: (query) Filter by subscriber status (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetSubscribers200Response> 
     */
    open class func getSubscribersWithRequestBuilder(listId: String, page: Int? = nil, perPage: Int? = nil, status: Status_getSubscribers? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<GetSubscribers200Response> {
        var localVariablePath = "/v1/lists/{list_id}/subscribers"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "per_page": (wrappedValue: perPage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSubscribers200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Subscribe to a list
     
     - parameter listId: (path) List UUID 
     - parameter subscribeRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UnsubscribeSubscriber200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func subscribe(listId: String, subscribeRequest: SubscribeRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> UnsubscribeSubscriber200Response {
        return try await subscribeWithRequestBuilder(listId: listId, subscribeRequest: subscribeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Subscribe to a list
     - POST /v1/subscribe/{list_id}
     - Add a subscriber to a list and initiate the double opt-in confirmation flow. The subscriber receives a confirmation email and must click the link to confirm. Rate limited to 10 requests/min per IP and 1000/hour per account.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) List UUID 
     - parameter subscribeRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UnsubscribeSubscriber200Response> 
     */
    open class func subscribeWithRequestBuilder(listId: String, subscribeRequest: SubscribeRequest, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<UnsubscribeSubscriber200Response> {
        var localVariablePath = "/v1/subscribe/{list_id}"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: subscribeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UnsubscribeSubscriber200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Unsubscribe a subscriber
     
     - parameter listId: (path) List UUID 
     - parameter subscriberId: (path) Subscriber UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UnsubscribeSubscriber200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func unsubscribeSubscriber(listId: String, subscriberId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> UnsubscribeSubscriber200Response {
        return try await unsubscribeSubscriberWithRequestBuilder(listId: listId, subscriberId: subscriberId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Unsubscribe a subscriber
     - DELETE /v1/lists/{list_id}/subscribers/{subscriber_id}
     - Set a subscriber's status to unsubscribed. The consent record is retained for compliance.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter listId: (path) List UUID 
     - parameter subscriberId: (path) Subscriber UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UnsubscribeSubscriber200Response> 
     */
    open class func unsubscribeSubscriberWithRequestBuilder(listId: String, subscriberId: String, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<UnsubscribeSubscriber200Response> {
        var localVariablePath = "/v1/lists/{list_id}/subscribers/{subscriber_id}"
        let listIdPreEscape = "\(APIHelper.mapValueToPathItem(listId))"
        let listIdPostEscape = listIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{list_id}", with: listIdPostEscape, options: .literal, range: nil)
        let subscriberIdPreEscape = "\(APIHelper.mapValueToPathItem(subscriberId))"
        let subscriberIdPostEscape = subscriberIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{subscriber_id}", with: subscriberIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UnsubscribeSubscriber200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
