//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SystemAPI {

    /**
     * enum for parameter window
     */
    public enum Window_getTelemetrySummary: String, Sendable, CaseIterable {
        case _1h = "1h"
        case _24h = "24h"
        case _30d = "30d"
    }

    /**
     Get validation telemetry
     
     - parameter window: (query) Time window for metrics (optional, default to ._24h)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TelemetrySummary
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getTelemetrySummary(window: Window_getTelemetrySummary? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> TelemetrySummary {
        return try await getTelemetrySummaryWithRequestBuilder(window: window, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get validation telemetry
     - GET /v1/telemetry/summary
     - Get validation metrics for your account. Useful for building dashboards and monitoring. Supports ETag caching.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [ETag(String), Cache-Control(String)]
     - parameter window: (query) Time window for metrics (optional, default to ._24h)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TelemetrySummary> 
     */
    open class func getTelemetrySummaryWithRequestBuilder(window: Window_getTelemetrySummary? = nil, apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<TelemetrySummary> {
        let localVariablePath = "/v1/telemetry/summary"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "window": (wrappedValue: window?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TelemetrySummary>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Health check
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: HealthCheck200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func healthCheck(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) async throws(ErrorResponse) -> HealthCheck200Response {
        return try await healthCheckWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Health check
     - GET /health
     - Check API health status. No authentication required.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<HealthCheck200Response> 
     */
    open class func healthCheckWithRequestBuilder(apiConfiguration: MailOddsAPIConfiguration = MailOddsAPIConfiguration.shared) -> RequestBuilder<HealthCheck200Response> {
        let localVariablePath = "/health"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthCheck200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
