//
// BounceAnalysisAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BounceAnalysisAPI {

    /**
     Analyze bounce logs
     
     - parameter createBounceAnalysisRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createBounceAnalysis(createBounceAnalysisRequest: CreateBounceAnalysisRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: BounceAnalysisResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createBounceAnalysisWithRequestBuilder(createBounceAnalysisRequest: createBounceAnalysisRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Analyze bounce logs
     - POST /v1/bounce-analyses
     - Submit bounce log data for analysis. Identifies patterns, categorizes bounce types, and provides remediation recommendations.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createBounceAnalysisRequest: (body)  
     - returns: RequestBuilder<BounceAnalysisResponse> 
     */
    open class func createBounceAnalysisWithRequestBuilder(createBounceAnalysisRequest: CreateBounceAnalysisRequest) -> RequestBuilder<BounceAnalysisResponse> {
        let localVariablePath = "/v1/bounce-analyses"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createBounceAnalysisRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BounceAnalysisResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Cross-reference bounces with validation logs
     
     - parameter analysisId: (path) Bounce analysis UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func crossReferenceBounces(analysisId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CrossReferenceBounces200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return crossReferenceBouncesWithRequestBuilder(analysisId: analysisId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cross-reference bounces with validation logs
     - GET /v1/bounce-analyses/{analysis_id}/cross-reference
     - Match bounced emails against your validation history to identify emails that were validated as deliverable but later bounced.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter analysisId: (path) Bounce analysis UUID 
     - returns: RequestBuilder<CrossReferenceBounces200Response> 
     */
    open class func crossReferenceBouncesWithRequestBuilder(analysisId: String) -> RequestBuilder<CrossReferenceBounces200Response> {
        var localVariablePath = "/v1/bounce-analyses/{analysis_id}/cross-reference"
        let analysisIdPreEscape = "\(APIHelper.mapValueToPathItem(analysisId))"
        let analysisIdPostEscape = analysisIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{analysis_id}", with: analysisIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CrossReferenceBounces200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete bounce analysis
     
     - parameter analysisId: (path) Bounce analysis ID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteBounceAnalysis(analysisId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeletePolicyRule200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteBounceAnalysisWithRequestBuilder(analysisId: analysisId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete bounce analysis
     - DELETE /v1/bounce-analyses/{analysis_id}
     - Delete a bounce analysis and all associated records.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter analysisId: (path) Bounce analysis ID 
     - returns: RequestBuilder<DeletePolicyRule200Response> 
     */
    open class func deleteBounceAnalysisWithRequestBuilder(analysisId: String) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/bounce-analyses/{analysis_id}"
        let analysisIdPreEscape = "\(APIHelper.mapValueToPathItem(analysisId))"
        let analysisIdPostEscape = analysisIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{analysis_id}", with: analysisIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get bounce analysis
     
     - parameter analysisId: (path) Bounce analysis UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getBounceAnalysis(analysisId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: BounceAnalysisResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getBounceAnalysisWithRequestBuilder(analysisId: analysisId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get bounce analysis
     - GET /v1/bounce-analyses/{analysis_id}
     - Get the results of a bounce analysis including category breakdown, top offenders, and recommendations.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter analysisId: (path) Bounce analysis UUID 
     - returns: RequestBuilder<BounceAnalysisResponse> 
     */
    open class func getBounceAnalysisWithRequestBuilder(analysisId: String) -> RequestBuilder<BounceAnalysisResponse> {
        var localVariablePath = "/v1/bounce-analyses/{analysis_id}"
        let analysisIdPreEscape = "\(APIHelper.mapValueToPathItem(analysisId))"
        let analysisIdPostEscape = analysisIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{analysis_id}", with: analysisIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BounceAnalysisResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_getBounceRecords: String, CaseIterable {
        case hard = "hard"
        case soft = "soft"
    }

    /**
     Get bounce records
     
     - parameter analysisId: (path) Bounce analysis UUID 
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 50)
     - parameter type: (query) Filter by bounce type (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getBounceRecords(analysisId: String, page: Int? = nil, perPage: Int? = nil, type: ModelType_getBounceRecords? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetBounceRecords200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getBounceRecordsWithRequestBuilder(analysisId: analysisId, page: page, perPage: perPage, type: type).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get bounce records
     - GET /v1/bounce-analyses/{analysis_id}/records
     - Get individual bounce records from an analysis with pagination.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter analysisId: (path) Bounce analysis UUID 
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 50)
     - parameter type: (query) Filter by bounce type (optional)
     - returns: RequestBuilder<GetBounceRecords200Response> 
     */
    open class func getBounceRecordsWithRequestBuilder(analysisId: String, page: Int? = nil, perPage: Int? = nil, type: ModelType_getBounceRecords? = nil) -> RequestBuilder<GetBounceRecords200Response> {
        var localVariablePath = "/v1/bounce-analyses/{analysis_id}/records"
        let analysisIdPreEscape = "\(APIHelper.mapValueToPathItem(analysisId))"
        let analysisIdPostEscape = analysisIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{analysis_id}", with: analysisIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "type": (wrappedValue: type?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetBounceRecords200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
