//
// BulkValidationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BulkValidationAPI {

    /**
     Cancel a job
     
     - parameter jobId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func cancelJob(jobId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JobResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return cancelJobWithRequestBuilder(jobId: jobId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel a job
     - POST /v1/jobs/{job_id}/cancel
     - Cancel a pending or processing job. Partial results are preserved.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter jobId: (path)  
     - returns: RequestBuilder<JobResponse> 
     */
    open class func cancelJobWithRequestBuilder(jobId: String) -> RequestBuilder<JobResponse> {
        var localVariablePath = "/v1/jobs/{job_id}/cancel"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{job_id}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create bulk validation job (JSON)
     
     - parameter createJobRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createJob(createJobRequest: CreateJobRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JobResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createJobWithRequestBuilder(createJobRequest: createJobRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create bulk validation job (JSON)
     - POST /v1/jobs
     - Create a new bulk validation job by submitting a JSON array of emails.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createJobRequest: (body)  
     - returns: RequestBuilder<JobResponse> 
     */
    open class func createJobWithRequestBuilder(createJobRequest: CreateJobRequest) -> RequestBuilder<JobResponse> {
        let localVariablePath = "/v1/jobs"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createJobRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create job from S3 upload
     
     - parameter createJobFromS3Request: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createJobFromS3(createJobFromS3Request: CreateJobFromS3Request, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JobResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createJobFromS3WithRequestBuilder(createJobFromS3Request: createJobFromS3Request).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create job from S3 upload
     - POST /v1/jobs/upload/s3
     - Create a validation job from a file previously uploaded to S3.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createJobFromS3Request: (body)  
     - returns: RequestBuilder<JobResponse> 
     */
    open class func createJobFromS3WithRequestBuilder(createJobFromS3Request: CreateJobFromS3Request) -> RequestBuilder<JobResponse> {
        let localVariablePath = "/v1/jobs/upload/s3"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createJobFromS3Request)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create bulk validation job (file upload)
     
     - parameter file: (form) CSV, Excel (.xlsx, .xls), ODS, or TXT file 
     - parameter dedup: (form) Remove duplicate emails (optional, default to false)
     - parameter metadata: (form) JSON metadata for the job (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createJobUpload(file: URL, dedup: Bool? = nil, metadata: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JobResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createJobUploadWithRequestBuilder(file: file, dedup: dedup, metadata: metadata).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create bulk validation job (file upload)
     - POST /v1/jobs/upload
     - Create a new bulk validation job by uploading a CSV, Excel, or TXT file.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter file: (form) CSV, Excel (.xlsx, .xls), ODS, or TXT file 
     - parameter dedup: (form) Remove duplicate emails (optional, default to false)
     - parameter metadata: (form) JSON metadata for the job (optional)
     - returns: RequestBuilder<JobResponse> 
     */
    open class func createJobUploadWithRequestBuilder(file: URL, dedup: Bool? = nil, metadata: String? = nil) -> RequestBuilder<JobResponse> {
        let localVariablePath = "/v1/jobs/upload"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
            "dedup": dedup?.encodeToJSON(),
            "metadata": metadata?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a job
     
     - parameter jobId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteJob(jobId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeleteJob200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteJobWithRequestBuilder(jobId: jobId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete a job
     - DELETE /v1/jobs/{job_id}
     - Permanently delete a completed or cancelled job and its results.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter jobId: (path)  
     - returns: RequestBuilder<DeleteJob200Response> 
     */
    open class func deleteJobWithRequestBuilder(jobId: String) -> RequestBuilder<DeleteJob200Response> {
        var localVariablePath = "/v1/jobs/{job_id}"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{job_id}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteJob200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get job status
     
     - parameter jobId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getJob(jobId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JobResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getJobWithRequestBuilder(jobId: jobId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get job status
     - GET /v1/jobs/{job_id}
     - Get the status and details of a specific validation job.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter jobId: (path)  
     - returns: RequestBuilder<JobResponse> 
     */
    open class func getJobWithRequestBuilder(jobId: String) -> RequestBuilder<JobResponse> {
        var localVariablePath = "/v1/jobs/{job_id}"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{job_id}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter format
     */
    public enum Format_getJobResults: String, CaseIterable {
        case json = "json"
        case csv = "csv"
        case ndjson = "ndjson"
    }

    /**
     * enum for parameter filter
     */
    public enum Filter_getJobResults: String, CaseIterable {
        case all = "all"
        case validOnly = "valid_only"
        case invalidOnly = "invalid_only"
    }

    /**
     Get job results
     
     - parameter jobId: (path)  
     - parameter format: (query)  (optional, default to .json)
     - parameter filter: (query)  (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 1000)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getJobResults(jobId: String, format: Format_getJobResults? = nil, filter: Filter_getJobResults? = nil, page: Int? = nil, perPage: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ResultsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getJobResultsWithRequestBuilder(jobId: jobId, format: format, filter: filter, page: page, perPage: perPage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get job results
     - GET /v1/jobs/{job_id}/results
     - Download validation results in JSON, CSV, or NDJSON format.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter jobId: (path)  
     - parameter format: (query)  (optional, default to .json)
     - parameter filter: (query)  (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 1000)
     - returns: RequestBuilder<ResultsResponse> 
     */
    open class func getJobResultsWithRequestBuilder(jobId: String, format: Format_getJobResults? = nil, filter: Filter_getJobResults? = nil, page: Int? = nil, perPage: Int? = nil) -> RequestBuilder<ResultsResponse> {
        var localVariablePath = "/v1/jobs/{job_id}/results"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{job_id}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "format": (wrappedValue: format?.encodeToJSON(), isExplode: true),
            "filter": (wrappedValue: filter?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResultsResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get S3 presigned upload URL
     
     - parameter getPresignedUploadRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPresignedUpload(getPresignedUploadRequest: GetPresignedUploadRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PresignedUploadResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPresignedUploadWithRequestBuilder(getPresignedUploadRequest: getPresignedUploadRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get S3 presigned upload URL
     - POST /v1/jobs/upload/presigned
     - Get a presigned URL for uploading large files (>10MB) directly to S3.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter getPresignedUploadRequest: (body)  
     - returns: RequestBuilder<PresignedUploadResponse> 
     */
    open class func getPresignedUploadWithRequestBuilder(getPresignedUploadRequest: GetPresignedUploadRequest) -> RequestBuilder<PresignedUploadResponse> {
        let localVariablePath = "/v1/jobs/upload/presigned"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getPresignedUploadRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PresignedUploadResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter status
     */
    public enum Status_listJobs: String, CaseIterable {
        case pending = "pending"
        case processing = "processing"
        case completed = "completed"
        case failed = "failed"
        case cancelled = "cancelled"
    }

    /**
     List validation jobs
     
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter status: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listJobs(page: Int? = nil, perPage: Int? = nil, status: Status_listJobs? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JobListResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return listJobsWithRequestBuilder(page: page, perPage: perPage, status: status).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List validation jobs
     - GET /v1/jobs
     - List all validation jobs for the authenticated account.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter status: (query)  (optional)
     - returns: RequestBuilder<JobListResponse> 
     */
    open class func listJobsWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, status: Status_listJobs? = nil) -> RequestBuilder<JobListResponse> {
        let localVariablePath = "/v1/jobs"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobListResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
