//
// CampaignsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CampaignsAPI {

    /**
     Cancel a campaign
     
     - parameter campaignId: (path) Campaign UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func cancelCampaign(campaignId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CampaignResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return cancelCampaignWithRequestBuilder(campaignId: campaignId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel a campaign
     - POST /v1/campaigns/{campaign_id}/cancel
     - Cancel a scheduled or in-progress campaign. Messages already delivered are not recalled.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter campaignId: (path) Campaign UUID 
     - returns: RequestBuilder<CampaignResponse> 
     */
    open class func cancelCampaignWithRequestBuilder(campaignId: String) -> RequestBuilder<CampaignResponse> {
        var localVariablePath = "/v1/campaigns/{campaign_id}/cancel"
        let campaignIdPreEscape = "\(APIHelper.mapValueToPathItem(campaignId))"
        let campaignIdPostEscape = campaignIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{campaign_id}", with: campaignIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CampaignResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a campaign
     
     - parameter createCampaignRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCampaign(createCampaignRequest: CreateCampaignRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CampaignResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createCampaignWithRequestBuilder(createCampaignRequest: createCampaignRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create a campaign
     - POST /v1/campaigns
     - Create a new email campaign. Campaigns target a subscriber list and support A/B variant testing.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createCampaignRequest: (body)  
     - returns: RequestBuilder<CampaignResponse> 
     */
    open class func createCampaignWithRequestBuilder(createCampaignRequest: CreateCampaignRequest) -> RequestBuilder<CampaignResponse> {
        let localVariablePath = "/v1/campaigns"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCampaignRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CampaignResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create A/B variant
     
     - parameter campaignId: (path) Campaign UUID 
     - parameter createVariantRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCampaignVariant(campaignId: String, createVariantRequest: CreateVariantRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateCampaignVariant201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createCampaignVariantWithRequestBuilder(campaignId: campaignId, createVariantRequest: createVariantRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create A/B variant
     - POST /v1/campaigns/{campaign_id}/variants
     - Add an A/B test variant to a campaign. Each variant has its own subject, body, and traffic weight. The campaign must be in draft status.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter campaignId: (path) Campaign UUID 
     - parameter createVariantRequest: (body)  
     - returns: RequestBuilder<CreateCampaignVariant201Response> 
     */
    open class func createCampaignVariantWithRequestBuilder(campaignId: String, createVariantRequest: CreateVariantRequest) -> RequestBuilder<CreateCampaignVariant201Response> {
        var localVariablePath = "/v1/campaigns/{campaign_id}/variants"
        let campaignIdPreEscape = "\(APIHelper.mapValueToPathItem(campaignId))"
        let campaignIdPostEscape = campaignIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{campaign_id}", with: campaignIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createVariantRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateCampaignVariant201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a campaign
     
     - parameter campaignId: (path) Campaign UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteCampaign(campaignId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeletePolicyRule200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteCampaignWithRequestBuilder(campaignId: campaignId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete a campaign
     - DELETE /v1/campaigns/{campaign_id}
     - Permanently delete a campaign. Only campaigns in draft, sent, failed, or cancelled status can be deleted.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter campaignId: (path) Campaign UUID 
     - returns: RequestBuilder<DeletePolicyRule200Response> 
     */
    open class func deleteCampaignWithRequestBuilder(campaignId: String) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/campaigns/{campaign_id}"
        let campaignIdPreEscape = "\(APIHelper.mapValueToPathItem(campaignId))"
        let campaignIdPostEscape = campaignIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{campaign_id}", with: campaignIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get campaign with stats
     
     - parameter campaignId: (path) Campaign UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCampaign(campaignId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CampaignResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getCampaignWithRequestBuilder(campaignId: campaignId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get campaign with stats
     - GET /v1/campaigns/{campaign_id}
     - Get a campaign by ID including delivery statistics and engagement metrics.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter campaignId: (path) Campaign UUID 
     - returns: RequestBuilder<CampaignResponse> 
     */
    open class func getCampaignWithRequestBuilder(campaignId: String) -> RequestBuilder<CampaignResponse> {
        var localVariablePath = "/v1/campaigns/{campaign_id}"
        let campaignIdPreEscape = "\(APIHelper.mapValueToPathItem(campaignId))"
        let campaignIdPostEscape = campaignIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{campaign_id}", with: campaignIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CampaignResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter status
     */
    public enum Status_listCampaigns: String, CaseIterable {
        case draft = "draft"
        case scheduled = "scheduled"
        case sending = "sending"
        case sent = "sent"
        case cancelled = "cancelled"
    }

    /**
     List campaigns
     
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 25)
     - parameter status: (query) Filter by campaign status (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listCampaigns(page: Int? = nil, perPage: Int? = nil, status: Status_listCampaigns? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ListCampaigns200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listCampaignsWithRequestBuilder(page: page, perPage: perPage, status: status).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List campaigns
     - GET /v1/campaigns
     - List all campaigns for the authenticated account with pagination.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter page: (query) Page number (optional, default to 1)
     - parameter perPage: (query) Items per page (optional, default to 25)
     - parameter status: (query) Filter by campaign status (optional)
     - returns: RequestBuilder<ListCampaigns200Response> 
     */
    open class func listCampaignsWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, status: Status_listCampaigns? = nil) -> RequestBuilder<ListCampaigns200Response> {
        let localVariablePath = "/v1/campaigns"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListCampaigns200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Schedule a campaign
     
     - parameter campaignId: (path) Campaign UUID 
     - parameter scheduleCampaignRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scheduleCampaign(campaignId: String, scheduleCampaignRequest: ScheduleCampaignRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CampaignResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return scheduleCampaignWithRequestBuilder(campaignId: campaignId, scheduleCampaignRequest: scheduleCampaignRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Schedule a campaign
     - POST /v1/campaigns/{campaign_id}/schedule
     - Schedule a campaign for future delivery. Provide a send_at timestamp in ISO 8601 format.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter campaignId: (path) Campaign UUID 
     - parameter scheduleCampaignRequest: (body)  
     - returns: RequestBuilder<CampaignResponse> 
     */
    open class func scheduleCampaignWithRequestBuilder(campaignId: String, scheduleCampaignRequest: ScheduleCampaignRequest) -> RequestBuilder<CampaignResponse> {
        var localVariablePath = "/v1/campaigns/{campaign_id}/schedule"
        let campaignIdPreEscape = "\(APIHelper.mapValueToPathItem(campaignId))"
        let campaignIdPostEscape = campaignIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{campaign_id}", with: campaignIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: scheduleCampaignRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CampaignResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a campaign
     
     - parameter campaignId: (path) Campaign UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func sendCampaign(campaignId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CampaignResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return sendCampaignWithRequestBuilder(campaignId: campaignId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Send a campaign
     - POST /v1/campaigns/{campaign_id}/send
     - Begin sending a campaign immediately. The campaign must be in draft status with at least one variant and a target list.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter campaignId: (path) Campaign UUID 
     - returns: RequestBuilder<CampaignResponse> 
     */
    open class func sendCampaignWithRequestBuilder(campaignId: String) -> RequestBuilder<CampaignResponse> {
        var localVariablePath = "/v1/campaigns/{campaign_id}/send"
        let campaignIdPreEscape = "\(APIHelper.mapValueToPathItem(campaignId))"
        let campaignIdPostEscape = campaignIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{campaign_id}", with: campaignIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CampaignResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
