//
// DMARCMonitoringAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DMARCMonitoringAPI {

    /**
     Add DMARC domain
     
     - parameter addDmarcDomainRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addDmarcDomain(addDmarcDomainRequest: AddDmarcDomainRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: AddDmarcDomain201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return addDmarcDomainWithRequestBuilder(addDmarcDomainRequest: addDmarcDomainRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add DMARC domain
     - POST /v1/dmarc-domains
     - Add a domain for DMARC monitoring. A unique reporting address is generated for receiving aggregate DMARC reports.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter addDmarcDomainRequest: (body)  
     - returns: RequestBuilder<AddDmarcDomain201Response> 
     */
    open class func addDmarcDomainWithRequestBuilder(addDmarcDomainRequest: AddDmarcDomainRequest) -> RequestBuilder<AddDmarcDomain201Response> {
        let localVariablePath = "/v1/dmarc-domains"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addDmarcDomainRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddDmarcDomain201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a DMARC domain
     
     - parameter domainId: (path) DMARC domain UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteDmarcDomain(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeletePolicyRule200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteDmarcDomainWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete a DMARC domain
     - DELETE /v1/dmarc-domains/{domain_id}
     - Delete a DMARC domain and all its associated reports.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) DMARC domain UUID 
     - returns: RequestBuilder<DeletePolicyRule200Response> 
     */
    open class func deleteDmarcDomainWithRequestBuilder(domainId: String) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/dmarc-domains/{domain_id}"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get DMARC domain
     
     - parameter domainId: (path) DMARC domain UUID 
     - parameter days: (query) Number of days for summary stats (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getDmarcDomain(domainId: String, days: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetDmarcDomain200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getDmarcDomainWithRequestBuilder(domainId: domainId, days: days).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get DMARC domain
     - GET /v1/dmarc-domains/{domain_id}
     - Get a single DMARC domain with summary statistics including pass/fail rates.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) DMARC domain UUID 
     - parameter days: (query) Number of days for summary stats (optional, default to 30)
     - returns: RequestBuilder<GetDmarcDomain200Response> 
     */
    open class func getDmarcDomainWithRequestBuilder(domainId: String, days: Int? = nil) -> RequestBuilder<GetDmarcDomain200Response> {
        var localVariablePath = "/v1/dmarc-domains/{domain_id}"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "days": (wrappedValue: days?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDmarcDomain200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get DMARC policy recommendation
     
     - parameter domainId: (path) DMARC domain UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getDmarcRecommendation(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetDmarcRecommendation200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getDmarcRecommendationWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get DMARC policy recommendation
     - GET /v1/dmarc-domains/{domain_id}/recommendation
     - Get a recommendation for upgrading the domain's DMARC policy based on alignment data.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) DMARC domain UUID 
     - returns: RequestBuilder<GetDmarcRecommendation200Response> 
     */
    open class func getDmarcRecommendationWithRequestBuilder(domainId: String) -> RequestBuilder<GetDmarcRecommendation200Response> {
        var localVariablePath = "/v1/dmarc-domains/{domain_id}/recommendation"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDmarcRecommendation200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get DMARC sending sources
     
     - parameter domainId: (path) DMARC domain UUID 
     - parameter days: (query) Number of days to look back (optional, default to 30)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getDmarcSources(domainId: String, days: Int? = nil, page: Int? = nil, perPage: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetDmarcSources200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getDmarcSourcesWithRequestBuilder(domainId: domainId, days: days, page: page, perPage: perPage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get DMARC sending sources
     - GET /v1/dmarc-domains/{domain_id}/sources
     - Get sending IPs that have sent email for this domain with their DKIM/SPF alignment status.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) DMARC domain UUID 
     - parameter days: (query) Number of days to look back (optional, default to 30)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - returns: RequestBuilder<GetDmarcSources200Response> 
     */
    open class func getDmarcSourcesWithRequestBuilder(domainId: String, days: Int? = nil, page: Int? = nil, perPage: Int? = nil) -> RequestBuilder<GetDmarcSources200Response> {
        var localVariablePath = "/v1/dmarc-domains/{domain_id}/sources"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "days": (wrappedValue: days?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDmarcSources200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get DMARC trend
     
     - parameter domainId: (path) DMARC domain UUID 
     - parameter days: (query) Number of days of trend data (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getDmarcTrend(domainId: String, days: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetDmarcTrend200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getDmarcTrendWithRequestBuilder(domainId: domainId, days: days).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get DMARC trend
     - GET /v1/dmarc-domains/{domain_id}/trend
     - Get daily pass/fail trend data for DMARC authentication over the specified period.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) DMARC domain UUID 
     - parameter days: (query) Number of days of trend data (optional, default to 30)
     - returns: RequestBuilder<GetDmarcTrend200Response> 
     */
    open class func getDmarcTrendWithRequestBuilder(domainId: String, days: Int? = nil) -> RequestBuilder<GetDmarcTrend200Response> {
        var localVariablePath = "/v1/dmarc-domains/{domain_id}/trend"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "days": (wrappedValue: days?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDmarcTrend200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List DMARC domains
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listDmarcDomains(apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ListDmarcDomains200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listDmarcDomainsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List DMARC domains
     - GET /v1/dmarc-domains
     - List all domains being monitored for DMARC compliance.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<ListDmarcDomains200Response> 
     */
    open class func listDmarcDomainsWithRequestBuilder() -> RequestBuilder<ListDmarcDomains200Response> {
        let localVariablePath = "/v1/dmarc-domains"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListDmarcDomains200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Verify DMARC DNS records
     
     - parameter domainId: (path) DMARC domain UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifyDmarcDomain(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: AddDmarcDomain201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return verifyDmarcDomainWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify DMARC DNS records
     - POST /v1/dmarc-domains/{domain_id}/verify
     - Check that the domain has the correct DMARC TXT record pointing to the MailOdds reporting address.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) DMARC domain UUID 
     - returns: RequestBuilder<AddDmarcDomain201Response> 
     */
    open class func verifyDmarcDomainWithRequestBuilder(domainId: String) -> RequestBuilder<AddDmarcDomain201Response> {
        var localVariablePath = "/v1/dmarc-domains/{domain_id}/verify"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddDmarcDomain201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
