//
// EngagementAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EngagementAPI {

    /**
     List disengaged contacts
     
     - parameter inactiveDays: (query) Days of inactivity (optional, default to 90)
     - parameter minSends: (query) Minimum emails sent to qualify (optional, default to 5)
     - parameter domainId: (query) Filter by sending domain ID (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 100)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getDisengagedContacts(inactiveDays: Int? = nil, minSends: Int? = nil, domainId: String? = nil, page: Int? = nil, perPage: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetDisengagedContacts200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getDisengagedContactsWithRequestBuilder(inactiveDays: inactiveDays, minSends: minSends, domainId: domainId, page: page, perPage: perPage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List disengaged contacts
     - GET /v1/engagement/disengaged
     - List contacts that have not engaged within the specified period. Requires Growth+ plan.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter inactiveDays: (query) Days of inactivity (optional, default to 90)
     - parameter minSends: (query) Minimum emails sent to qualify (optional, default to 5)
     - parameter domainId: (query) Filter by sending domain ID (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 100)
     - returns: RequestBuilder<GetDisengagedContacts200Response> 
     */
    open class func getDisengagedContactsWithRequestBuilder(inactiveDays: Int? = nil, minSends: Int? = nil, domainId: String? = nil, page: Int? = nil, perPage: Int? = nil) -> RequestBuilder<GetDisengagedContacts200Response> {
        let localVariablePath = "/v1/engagement/disengaged"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inactive_days": (wrappedValue: inactiveDays?.encodeToJSON(), isExplode: true),
            "min_sends": (wrappedValue: minSends?.encodeToJSON(), isExplode: true),
            "domain_id": (wrappedValue: domainId?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDisengagedContacts200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get engagement score
     
     - parameter email: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getEngagementScore(email: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetEngagementScore200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getEngagementScoreWithRequestBuilder(email: email).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get engagement score
     - GET /v1/engagement/score/{email}
     - Get the engagement score for a specific email address. Requires Growth+ plan.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter email: (path)  
     - returns: RequestBuilder<GetEngagementScore200Response> 
     */
    open class func getEngagementScoreWithRequestBuilder(email: String) -> RequestBuilder<GetEngagementScore200Response> {
        var localVariablePath = "/v1/engagement/score/{email}"
        let emailPreEscape = "\(APIHelper.mapValueToPathItem(email))"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetEngagementScore200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get engagement summary
     
     - parameter domainId: (query) Filter by sending domain ID (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getEngagementSummary(domainId: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetBounceStatsSummary200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getEngagementSummaryWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get engagement summary
     - GET /v1/engagement/summary
     - Get aggregate engagement metrics across all contacts. Requires Growth+ plan.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (query) Filter by sending domain ID (optional)
     - returns: RequestBuilder<GetBounceStatsSummary200Response> 
     */
    open class func getEngagementSummaryWithRequestBuilder(domainId: String? = nil) -> RequestBuilder<GetBounceStatsSummary200Response> {
        let localVariablePath = "/v1/engagement/summary"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain_id": (wrappedValue: domainId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetBounceStatsSummary200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Suppress disengaged contacts
     
     - parameter suppressDisengagedRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func suppressDisengaged(suppressDisengagedRequest: SuppressDisengagedRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: SuppressDisengaged200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return suppressDisengagedWithRequestBuilder(suppressDisengagedRequest: suppressDisengagedRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Suppress disengaged contacts
     - POST /v1/engagement/suppress-disengaged
     - Add disengaged contacts to the suppression list. Supports dry_run mode. Requires Growth+ plan.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter suppressDisengagedRequest: (body)  
     - returns: RequestBuilder<SuppressDisengaged200Response> 
     */
    open class func suppressDisengagedWithRequestBuilder(suppressDisengagedRequest: SuppressDisengagedRequest) -> RequestBuilder<SuppressDisengaged200Response> {
        let localVariablePath = "/v1/engagement/suppress-disengaged"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: suppressDisengagedRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuppressDisengaged200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
