//
// OAuth20API.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OAuth20API {

    /**
     * enum for parameter grantType
     */
    public enum GrantType_createToken: String, CaseIterable {
        case authorizationCode = "authorization_code"
        case clientCredentials = "client_credentials"
        case refreshToken = "refresh_token"
    }

    /**
     Create token
     
     - parameter grantType: (form)  
     - parameter code: (form) Authorization code (for authorization_code grant) (optional)
     - parameter redirectUri: (form) Must match the original redirect_uri (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter refreshToken: (form) Refresh token (for refresh_token grant) (optional)
     - parameter scope: (form) Space-separated scopes (optional)
     - parameter codeVerifier: (form) PKCE code verifier (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createToken(grantType: GrantType_createToken, code: String? = nil, redirectUri: String? = nil, clientId: String? = nil, clientSecret: String? = nil, refreshToken: String? = nil, scope: String? = nil, codeVerifier: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateToken200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createTokenWithRequestBuilder(grantType: grantType, code: code, redirectUri: redirectUri, clientId: clientId, clientSecret: clientSecret, refreshToken: refreshToken, scope: scope, codeVerifier: codeVerifier).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create token
     - POST /oauth/token
     - Exchange an authorization code, client credentials, or refresh token for access and refresh tokens. Authenticate via client_secret_post or client_secret_basic.
     - parameter grantType: (form)  
     - parameter code: (form) Authorization code (for authorization_code grant) (optional)
     - parameter redirectUri: (form) Must match the original redirect_uri (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter refreshToken: (form) Refresh token (for refresh_token grant) (optional)
     - parameter scope: (form) Space-separated scopes (optional)
     - parameter codeVerifier: (form) PKCE code verifier (optional)
     - returns: RequestBuilder<CreateToken200Response> 
     */
    open class func createTokenWithRequestBuilder(grantType: GrantType_createToken, code: String? = nil, redirectUri: String? = nil, clientId: String? = nil, clientSecret: String? = nil, refreshToken: String? = nil, scope: String? = nil, codeVerifier: String? = nil) -> RequestBuilder<CreateToken200Response> {
        let localVariablePath = "/oauth/token"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "grant_type": grantType.encodeToJSON(),
            "code": code?.encodeToJSON(),
            "redirect_uri": redirectUri?.encodeToJSON(),
            "client_id": clientId?.encodeToJSON(),
            "client_secret": clientSecret?.encodeToJSON(),
            "refresh_token": refreshToken?.encodeToJSON(),
            "scope": scope?.encodeToJSON(),
            "code_verifier": codeVerifier?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateToken200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get JSON Web Key Set
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getJwks(apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: JwksResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getJwksWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get JSON Web Key Set
     - GET /.well-known/jwks.json
     - Public key set for verifying JWT access tokens issued by this server.
     - returns: RequestBuilder<JwksResponse> 
     */
    open class func getJwksWithRequestBuilder() -> RequestBuilder<JwksResponse> {
        let localVariablePath = "/.well-known/jwks.json"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JwksResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter tokenTypeHint
     */
    public enum TokenTypeHint_introspectToken: String, CaseIterable {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
    }

    /**
     Introspect token
     
     - parameter token: (form) Token to introspect 
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func introspectToken(token: String, tokenTypeHint: TokenTypeHint_introspectToken? = nil, clientId: String? = nil, clientSecret: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: IntrospectToken200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return introspectTokenWithRequestBuilder(token: token, tokenTypeHint: tokenTypeHint, clientId: clientId, clientSecret: clientSecret).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Introspect token
     - POST /oauth/introspect
     - Introspect a token to determine its active state and metadata (RFC 7662). Requires client authentication.
     - parameter token: (form) Token to introspect 
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - returns: RequestBuilder<IntrospectToken200Response> 
     */
    open class func introspectTokenWithRequestBuilder(token: String, tokenTypeHint: TokenTypeHint_introspectToken? = nil, clientId: String? = nil, clientSecret: String? = nil) -> RequestBuilder<IntrospectToken200Response> {
        let localVariablePath = "/oauth/introspect"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "token": token.encodeToJSON(),
            "token_type_hint": tokenTypeHint?.encodeToJSON(),
            "client_id": clientId?.encodeToJSON(),
            "client_secret": clientSecret?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntrospectToken200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     OAuth server metadata
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func oauthServerMetadata(apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: OAuthServerMetadata?, _ error: Error?) -> Void)) -> RequestTask {
        return oauthServerMetadataWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     OAuth server metadata
     - GET /.well-known/oauth-authorization-server
     - OAuth 2.0 Authorization Server Metadata (RFC 8414). Returns server configuration including supported grant types, scopes, and endpoints.
     - returns: RequestBuilder<OAuthServerMetadata> 
     */
    open class func oauthServerMetadataWithRequestBuilder() -> RequestBuilder<OAuthServerMetadata> {
        let localVariablePath = "/.well-known/oauth-authorization-server"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuthServerMetadata>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter tokenTypeHint
     */
    public enum TokenTypeHint_revokeToken: String, CaseIterable {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
    }

    /**
     Revoke token
     
     - parameter token: (form) Token to revoke 
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func revokeToken(token: String, tokenTypeHint: TokenTypeHint_revokeToken? = nil, clientId: String? = nil, clientSecret: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return revokeTokenWithRequestBuilder(token: token, tokenTypeHint: tokenTypeHint, clientId: clientId, clientSecret: clientSecret).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Revoke token
     - POST /oauth/revoke
     - Revoke an access or refresh token (RFC 7009). Requires client authentication. Always returns 200 per spec to prevent token scanning.
     - parameter token: (form) Token to revoke 
     - parameter tokenTypeHint: (form)  (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func revokeTokenWithRequestBuilder(token: String, tokenTypeHint: TokenTypeHint_revokeToken? = nil, clientId: String? = nil, clientSecret: String? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/oauth/revoke"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "token": token.encodeToJSON(),
            "token_type_hint": tokenTypeHint?.encodeToJSON(),
            "client_id": clientId?.encodeToJSON(),
            "client_secret": clientSecret?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MailOddsAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
