//
// SendingDomainsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SendingDomainsAPI {

    /**
     Add a sending domain
     
     - parameter createSendingDomainRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createSendingDomain(createSendingDomainRequest: CreateSendingDomainRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateSendingDomain201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createSendingDomainWithRequestBuilder(createSendingDomainRequest: createSendingDomainRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add a sending domain
     - POST /v1/sending-domains
     - Register a new sending domain with NS delegation. After adding, configure DNS records and verify.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createSendingDomainRequest: (body)  
     - returns: RequestBuilder<CreateSendingDomain201Response> 
     */
    open class func createSendingDomainWithRequestBuilder(createSendingDomainRequest: CreateSendingDomainRequest) -> RequestBuilder<CreateSendingDomain201Response> {
        let localVariablePath = "/v1/sending-domains"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createSendingDomainRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateSendingDomain201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a sending domain
     
     - parameter domainId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteSendingDomain(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeletePolicyRule200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteSendingDomainWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete a sending domain
     - DELETE /v1/sending-domains/{domain_id}
     - Permanently remove a sending domain from the account.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path)  
     - returns: RequestBuilder<DeletePolicyRule200Response> 
     */
    open class func deleteSendingDomainWithRequestBuilder(domainId: String) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/sending-domains/{domain_id}"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get reply forwarding config
     
     - parameter domainId: (path) Sending domain ID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getReplyForwarding(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetReplyForwarding200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getReplyForwardingWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get reply forwarding config
     - GET /v1/sending-domains/{domain_id}/reply-forwarding
     - Get the reply forwarding configuration for a sending domain. Requires Growth+ plan.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) Sending domain ID 
     - returns: RequestBuilder<GetReplyForwarding200Response> 
     */
    open class func getReplyForwardingWithRequestBuilder(domainId: String) -> RequestBuilder<GetReplyForwarding200Response> {
        var localVariablePath = "/v1/sending-domains/{domain_id}/reply-forwarding"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetReplyForwarding200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a sending domain
     
     - parameter domainId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSendingDomain(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateSendingDomain201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSendingDomainWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a sending domain
     - GET /v1/sending-domains/{domain_id}
     - Get details of a specific sending domain including DNS verification status.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path)  
     - returns: RequestBuilder<CreateSendingDomain201Response> 
     */
    open class func getSendingDomainWithRequestBuilder(domainId: String) -> RequestBuilder<CreateSendingDomain201Response> {
        var localVariablePath = "/v1/sending-domains/{domain_id}"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateSendingDomain201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get domain identity score
     
     - parameter domainId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSendingDomainIdentityScore(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetSendingDomainIdentityScore200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSendingDomainIdentityScoreWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get domain identity score
     - GET /v1/sending-domains/{domain_id}/identity-score
     - Get a composite DNS health score for the sending domain, checking DKIM, SPF, DMARC, MX, and return path configuration.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path)  
     - returns: RequestBuilder<GetSendingDomainIdentityScore200Response> 
     */
    open class func getSendingDomainIdentityScoreWithRequestBuilder(domainId: String) -> RequestBuilder<GetSendingDomainIdentityScore200Response> {
        var localVariablePath = "/v1/sending-domains/{domain_id}/identity-score"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSendingDomainIdentityScore200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter period
     */
    public enum Period_getSendingStats: String, CaseIterable {
        case _7d = "7d"
        case _30d = "30d"
        case _90d = "90d"
    }

    /**
     Get sending statistics
     
     - parameter period: (query) Time period (optional, default to ._7d)
     - parameter domainId: (query) Filter by domain (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSendingStats(period: Period_getSendingStats? = nil, domainId: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetSendingStats200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSendingStatsWithRequestBuilder(period: period, domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get sending statistics
     - GET /v1/sending-stats
     - Get aggregate sending statistics across all domains for the account, including delivery rates, open rates, and click rates.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter period: (query) Time period (optional, default to ._7d)
     - parameter domainId: (query) Filter by domain (optional)
     - returns: RequestBuilder<GetSendingStats200Response> 
     */
    open class func getSendingStatsWithRequestBuilder(period: Period_getSendingStats? = nil, domainId: String? = nil) -> RequestBuilder<GetSendingStats200Response> {
        let localVariablePath = "/v1/sending-stats"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
            "domain_id": (wrappedValue: domainId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSendingStats200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List sending domains
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listSendingDomains(apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ListSendingDomains200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listSendingDomainsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List sending domains
     - GET /v1/sending-domains
     - List all sending domains for the authenticated account.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<ListSendingDomains200Response> 
     */
    open class func listSendingDomainsWithRequestBuilder() -> RequestBuilder<ListSendingDomains200Response> {
        let localVariablePath = "/v1/sending-domains"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListSendingDomains200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update reply forwarding config
     
     - parameter domainId: (path) Sending domain ID 
     - parameter updateReplyForwardingRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateReplyForwarding(domainId: String, updateReplyForwardingRequest: UpdateReplyForwardingRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetReplyForwarding200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return updateReplyForwardingWithRequestBuilder(domainId: domainId, updateReplyForwardingRequest: updateReplyForwardingRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update reply forwarding config
     - PATCH /v1/sending-domains/{domain_id}/reply-forwarding
     - Configure reply forwarding for a sending domain. Set forward_replies_to to null to disable. Requires Growth+ plan.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path) Sending domain ID 
     - parameter updateReplyForwardingRequest: (body)  
     - returns: RequestBuilder<GetReplyForwarding200Response> 
     */
    open class func updateReplyForwardingWithRequestBuilder(domainId: String, updateReplyForwardingRequest: UpdateReplyForwardingRequest) -> RequestBuilder<GetReplyForwarding200Response> {
        var localVariablePath = "/v1/sending-domains/{domain_id}/reply-forwarding"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateReplyForwardingRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetReplyForwarding200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Verify domain DNS records
     
     - parameter domainId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifySendingDomain(domainId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateSendingDomain201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return verifySendingDomainWithRequestBuilder(domainId: domainId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify domain DNS records
     - POST /v1/sending-domains/{domain_id}/verify
     - Check and verify all DNS records (DKIM, SPF, DMARC, MX, return path) for the sending domain.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter domainId: (path)  
     - returns: RequestBuilder<CreateSendingDomain201Response> 
     */
    open class func verifySendingDomainWithRequestBuilder(domainId: String) -> RequestBuilder<CreateSendingDomain201Response> {
        var localVariablePath = "/v1/sending-domains/{domain_id}/verify"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain_id}", with: domainIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateSendingDomain201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
