//
// StoreConnectionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StoreConnectionsAPI {

    /**
     Create a store connection
     
     - parameter createStoreRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createStore(createStoreRequest: CreateStoreRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateStore201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createStoreWithRequestBuilder(createStoreRequest: createStoreRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create a store connection
     - POST /v1/stores
     - Connect an e-commerce store (WooCommerce, PrestaShop, Shopify, or product feed). After creation, trigger a sync to import products.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createStoreRequest: (body)  
     - returns: RequestBuilder<CreateStore201Response> 
     */
    open class func createStoreWithRequestBuilder(createStoreRequest: CreateStoreRequest) -> RequestBuilder<CreateStore201Response> {
        let localVariablePath = "/v1/stores"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createStoreRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateStore201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Disconnect a store
     
     - parameter storeId: (path) Store connection UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func disconnectStore(storeId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DisconnectStore200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return disconnectStoreWithRequestBuilder(storeId: storeId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Disconnect a store
     - DELETE /v1/stores/{store_id}
     - Disconnect a store and deactivate its products. Products are retained but marked inactive.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID 
     - returns: RequestBuilder<DisconnectStore200Response> 
     */
    open class func disconnectStoreWithRequestBuilder(storeId: String) -> RequestBuilder<DisconnectStore200Response> {
        var localVariablePath = "/v1/stores/{store_id}"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisconnectStore200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a store connection
     
     - parameter storeId: (path) Store connection UUID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getStore(storeId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateStore201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getStoreWithRequestBuilder(storeId: storeId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a store connection
     - GET /v1/stores/{store_id}
     - Get details of a specific store connection including sync status and product count.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID 
     - returns: RequestBuilder<CreateStore201Response> 
     */
    open class func getStoreWithRequestBuilder(storeId: String) -> RequestBuilder<CreateStore201Response> {
        var localVariablePath = "/v1/stores/{store_id}"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateStore201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get sync job errors
     
     - parameter storeId: (path) Store ID 
     - parameter jobId: (path) Sync job ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 50)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSyncJobErrors(storeId: String, jobId: String, page: Int? = nil, perPage: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: GetSyncJobErrors200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSyncJobErrorsWithRequestBuilder(storeId: storeId, jobId: jobId, page: page, perPage: perPage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get sync job errors
     - GET /v1/stores/{store_id}/sync-jobs/{job_id}/errors
     - Get error details for a sync job.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store ID 
     - parameter jobId: (path) Sync job ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 50)
     - returns: RequestBuilder<GetSyncJobErrors200Response> 
     */
    open class func getSyncJobErrorsWithRequestBuilder(storeId: String, jobId: String, page: Int? = nil, perPage: Int? = nil) -> RequestBuilder<GetSyncJobErrors200Response> {
        var localVariablePath = "/v1/stores/{store_id}/sync-jobs/{job_id}/errors"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{job_id}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSyncJobErrors200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter status
     */
    public enum Status_listStores: String, CaseIterable {
        case active = "active"
        case disconnected = "disconnected"
        case pending = "pending"
        case error = "error"
    }

    /**
     List store connections
     
     - parameter status: (query) Filter by connection status (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listStores(status: Status_listStores? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ListStores200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listStoresWithRequestBuilder(status: status).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List store connections
     - GET /v1/stores
     - List all store connections for the authenticated account. Optionally filter by status.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter status: (query) Filter by connection status (optional)
     - returns: RequestBuilder<ListStores200Response> 
     */
    open class func listStoresWithRequestBuilder(status: Status_listStores? = nil) -> RequestBuilder<ListStores200Response> {
        let localVariablePath = "/v1/stores"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListStores200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List sync jobs
     
     - parameter storeId: (path) Store ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listSyncJobs(storeId: String, page: Int? = nil, perPage: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ListSyncJobs200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listSyncJobsWithRequestBuilder(storeId: storeId, page: page, perPage: perPage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List sync jobs
     - GET /v1/stores/{store_id}/sync-jobs
     - List sync job history for a store.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store ID 
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 20)
     - returns: RequestBuilder<ListSyncJobs200Response> 
     */
    open class func listSyncJobsWithRequestBuilder(storeId: String, page: Int? = nil, perPage: Int? = nil) -> RequestBuilder<ListSyncJobs200Response> {
        var localVariablePath = "/v1/stores/{store_id}/sync-jobs"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListSyncJobs200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Trigger product sync
     
     - parameter storeId: (path) Store connection UUID 
     - parameter idempotencyKey: (header) Idempotency key to prevent duplicate syncs (5 min TTL) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func triggerSync(storeId: String, idempotencyKey: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: SyncResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return triggerSyncWithRequestBuilder(storeId: storeId, idempotencyKey: idempotencyKey).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Trigger product sync
     - POST /v1/stores/{store_id}/sync
     - Trigger a manual product sync for a store. Supports idempotency via the Idempotency-Key header (5 minute TTL).
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID 
     - parameter idempotencyKey: (header) Idempotency key to prevent duplicate syncs (5 min TTL) (optional)
     - returns: RequestBuilder<SyncResponse> 
     */
    open class func triggerSyncWithRequestBuilder(storeId: String, idempotencyKey: String? = nil) -> RequestBuilder<SyncResponse> {
        var localVariablePath = "/v1/stores/{store_id}/sync"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SyncResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a store connection
     
     - parameter storeId: (path) Store connection UUID 
     - parameter updateStoreRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateStore(storeId: String, updateStoreRequest: UpdateStoreRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateStore201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return updateStoreWithRequestBuilder(storeId: storeId, updateStoreRequest: updateStoreRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update a store connection
     - PUT /v1/stores/{store_id}
     - Update store settings such as name, sync interval, or credentials.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter storeId: (path) Store connection UUID 
     - parameter updateStoreRequest: (body)  
     - returns: RequestBuilder<CreateStore201Response> 
     */
    open class func updateStoreWithRequestBuilder(storeId: String, updateStoreRequest: UpdateStoreRequest) -> RequestBuilder<CreateStore201Response> {
        var localVariablePath = "/v1/stores/{store_id}"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateStoreRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateStore201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
