//
// SuppressionListsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SuppressionListsAPI {

    /**
     Add suppression entries
     
     - parameter addSuppressionRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addSuppression(addSuppressionRequest: AddSuppressionRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: AddSuppressionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return addSuppressionWithRequestBuilder(addSuppressionRequest: addSuppressionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add suppression entries
     - POST /v1/suppression
     - Add emails or domains to the suppression list.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter addSuppressionRequest: (body)  
     - returns: RequestBuilder<AddSuppressionResponse> 
     */
    open class func addSuppressionWithRequestBuilder(addSuppressionRequest: AddSuppressionRequest) -> RequestBuilder<AddSuppressionResponse> {
        let localVariablePath = "/v1/suppression"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addSuppressionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddSuppressionResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Check suppression status
     
     - parameter checkSuppressionRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func checkSuppression(checkSuppressionRequest: CheckSuppressionRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: SuppressionCheckResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return checkSuppressionWithRequestBuilder(checkSuppressionRequest: checkSuppressionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check suppression status
     - POST /v1/suppression/check
     - Check if an email is suppressed.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter checkSuppressionRequest: (body)  
     - returns: RequestBuilder<SuppressionCheckResponse> 
     */
    open class func checkSuppressionWithRequestBuilder(checkSuppressionRequest: CheckSuppressionRequest) -> RequestBuilder<SuppressionCheckResponse> {
        let localVariablePath = "/v1/suppression/check"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: checkSuppressionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuppressionCheckResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get suppression statistics
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSuppressionStats(apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: SuppressionStatsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getSuppressionStatsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get suppression statistics
     - GET /v1/suppression/stats
     - Get statistics about the suppression list.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<SuppressionStatsResponse> 
     */
    open class func getSuppressionStatsWithRequestBuilder() -> RequestBuilder<SuppressionStatsResponse> {
        let localVariablePath = "/v1/suppression/stats"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuppressionStatsResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_listSuppression: String, CaseIterable {
        case email = "email"
        case domain = "domain"
    }

    /**
     List suppression entries
     
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 50)
     - parameter type: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listSuppression(page: Int? = nil, perPage: Int? = nil, type: ModelType_listSuppression? = nil, search: String? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: SuppressionListResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return listSuppressionWithRequestBuilder(page: page, perPage: perPage, type: type, search: search).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List suppression entries
     - GET /v1/suppression
     - List all suppression entries for the account.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter page: (query)  (optional, default to 1)
     - parameter perPage: (query)  (optional, default to 50)
     - parameter type: (query)  (optional)
     - parameter search: (query)  (optional)
     - returns: RequestBuilder<SuppressionListResponse> 
     */
    open class func listSuppressionWithRequestBuilder(page: Int? = nil, perPage: Int? = nil, type: ModelType_listSuppression? = nil, search: String? = nil) -> RequestBuilder<SuppressionListResponse> {
        let localVariablePath = "/v1/suppression"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "type": (wrappedValue: type?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuppressionListResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remove suppression entries
     
     - parameter removeSuppressionRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func removeSuppression(removeSuppressionRequest: RemoveSuppressionRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: RemoveSuppression200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return removeSuppressionWithRequestBuilder(removeSuppressionRequest: removeSuppressionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Remove suppression entries
     - DELETE /v1/suppression
     - Remove emails or domains from the suppression list.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter removeSuppressionRequest: (body)  
     - returns: RequestBuilder<RemoveSuppression200Response> 
     */
    open class func removeSuppressionWithRequestBuilder(removeSuppressionRequest: RemoveSuppressionRequest) -> RequestBuilder<RemoveSuppression200Response> {
        let localVariablePath = "/v1/suppression"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: removeSuppressionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RemoveSuppression200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
