//
// ValidationPoliciesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ValidationPoliciesAPI {

    /**
     Add rule to policy
     
     - parameter policyId: (path)  
     - parameter policyRule: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addPolicyRule(policyId: Int, policyRule: PolicyRule, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: AddPolicyRule201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return addPolicyRuleWithRequestBuilder(policyId: policyId, policyRule: policyRule).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add rule to policy
     - POST /v1/policies/{policy_id}/rules
     - Add a new rule to an existing policy.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter policyId: (path)  
     - parameter policyRule: (body)  
     - returns: RequestBuilder<AddPolicyRule201Response> 
     */
    open class func addPolicyRuleWithRequestBuilder(policyId: Int, policyRule: PolicyRule) -> RequestBuilder<AddPolicyRule201Response> {
        var localVariablePath = "/v1/policies/{policy_id}/rules"
        let policyIdPreEscape = "\(APIHelper.mapValueToPathItem(policyId))"
        let policyIdPostEscape = policyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_id}", with: policyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: policyRule)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddPolicyRule201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create policy
     
     - parameter createPolicyRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPolicy(createPolicyRequest: CreatePolicyRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createPolicyWithRequestBuilder(createPolicyRequest: createPolicyRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create policy
     - POST /v1/policies
     - Create a new validation policy with rules.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createPolicyRequest: (body)  
     - returns: RequestBuilder<PolicyResponse> 
     */
    open class func createPolicyWithRequestBuilder(createPolicyRequest: CreatePolicyRequest) -> RequestBuilder<PolicyResponse> {
        let localVariablePath = "/v1/policies"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createPolicyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create policy from preset
     
     - parameter createPolicyFromPresetRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPolicyFromPreset(createPolicyFromPresetRequest: CreatePolicyFromPresetRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createPolicyFromPresetWithRequestBuilder(createPolicyFromPresetRequest: createPolicyFromPresetRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create policy from preset
     - POST /v1/policies/from-preset
     - Create a policy using a preset template.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createPolicyFromPresetRequest: (body)  
     - returns: RequestBuilder<PolicyResponse> 
     */
    open class func createPolicyFromPresetWithRequestBuilder(createPolicyFromPresetRequest: CreatePolicyFromPresetRequest) -> RequestBuilder<PolicyResponse> {
        let localVariablePath = "/v1/policies/from-preset"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createPolicyFromPresetRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete policy
     
     - parameter policyId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePolicy(policyId: Int, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeletePolicy200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePolicyWithRequestBuilder(policyId: policyId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete policy
     - DELETE /v1/policies/{policy_id}
     - Delete a policy and all its rules.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter policyId: (path)  
     - returns: RequestBuilder<DeletePolicy200Response> 
     */
    open class func deletePolicyWithRequestBuilder(policyId: Int) -> RequestBuilder<DeletePolicy200Response> {
        var localVariablePath = "/v1/policies/{policy_id}"
        let policyIdPreEscape = "\(APIHelper.mapValueToPathItem(policyId))"
        let policyIdPostEscape = policyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_id}", with: policyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicy200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete rule
     
     - parameter policyId: (path)  
     - parameter ruleId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePolicyRule(policyId: Int, ruleId: Int, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeletePolicyRule200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePolicyRuleWithRequestBuilder(policyId: policyId, ruleId: ruleId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete rule
     - DELETE /v1/policies/{policy_id}/rules/{rule_id}
     - Delete a rule from a policy.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter policyId: (path)  
     - parameter ruleId: (path)  
     - returns: RequestBuilder<DeletePolicyRule200Response> 
     */
    open class func deletePolicyRuleWithRequestBuilder(policyId: Int, ruleId: Int) -> RequestBuilder<DeletePolicyRule200Response> {
        var localVariablePath = "/v1/policies/{policy_id}/rules/{rule_id}"
        let policyIdPreEscape = "\(APIHelper.mapValueToPathItem(policyId))"
        let policyIdPostEscape = policyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_id}", with: policyIdPostEscape, options: .literal, range: nil)
        let ruleIdPreEscape = "\(APIHelper.mapValueToPathItem(ruleId))"
        let ruleIdPostEscape = ruleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rule_id}", with: ruleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeletePolicyRule200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get policy
     
     - parameter policyId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPolicy(policyId: Int, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPolicyWithRequestBuilder(policyId: policyId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get policy
     - GET /v1/policies/{policy_id}
     - Get a single policy with its rules.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter policyId: (path)  
     - returns: RequestBuilder<PolicyResponse> 
     */
    open class func getPolicyWithRequestBuilder(policyId: Int) -> RequestBuilder<PolicyResponse> {
        var localVariablePath = "/v1/policies/{policy_id}"
        let policyIdPreEscape = "\(APIHelper.mapValueToPathItem(policyId))"
        let policyIdPostEscape = policyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_id}", with: policyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get policy presets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPolicyPresets(apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyPresetsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getPolicyPresetsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get policy presets
     - GET /v1/policies/presets
     - Get available preset templates for quick policy creation.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<PolicyPresetsResponse> 
     */
    open class func getPolicyPresetsWithRequestBuilder() -> RequestBuilder<PolicyPresetsResponse> {
        let localVariablePath = "/v1/policies/presets"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyPresetsResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List policies
     
     - parameter includeRules: (query) Include full rules in response (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listPolicies(includeRules: Bool? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyListResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return listPoliciesWithRequestBuilder(includeRules: includeRules).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List policies
     - GET /v1/policies
     - List all validation policies for your account. Includes plan limits.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter includeRules: (query) Include full rules in response (optional, default to false)
     - returns: RequestBuilder<PolicyListResponse> 
     */
    open class func listPoliciesWithRequestBuilder(includeRules: Bool? = nil) -> RequestBuilder<PolicyListResponse> {
        let localVariablePath = "/v1/policies"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "include_rules": (wrappedValue: includeRules?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyListResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Test policy evaluation
     
     - parameter testPolicyRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func testPolicy(testPolicyRequest: TestPolicyRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyTestResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return testPolicyWithRequestBuilder(testPolicyRequest: testPolicyRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Test policy evaluation
     - POST /v1/policies/test
     - Test how a policy would evaluate a validation result without affecting production.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter testPolicyRequest: (body)  
     - returns: RequestBuilder<PolicyTestResponse> 
     */
    open class func testPolicyWithRequestBuilder(testPolicyRequest: TestPolicyRequest) -> RequestBuilder<PolicyTestResponse> {
        let localVariablePath = "/v1/policies/test"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testPolicyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyTestResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update policy
     
     - parameter policyId: (path)  
     - parameter updatePolicyRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updatePolicy(policyId: Int, updatePolicyRequest: UpdatePolicyRequest, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: PolicyResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return updatePolicyWithRequestBuilder(policyId: policyId, updatePolicyRequest: updatePolicyRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update policy
     - PUT /v1/policies/{policy_id}
     - Update a policy's settings (name, enabled, default).
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter policyId: (path)  
     - parameter updatePolicyRequest: (body)  
     - returns: RequestBuilder<PolicyResponse> 
     */
    open class func updatePolicyWithRequestBuilder(policyId: Int, updatePolicyRequest: UpdatePolicyRequest) -> RequestBuilder<PolicyResponse> {
        var localVariablePath = "/v1/policies/{policy_id}"
        let policyIdPreEscape = "\(APIHelper.mapValueToPathItem(policyId))"
        let policyIdPostEscape = policyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{policy_id}", with: policyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updatePolicyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PolicyResponse>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
