//
// WebhookCLIAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class WebhookCLIAPI {

    /**
     Create CLI forwarding session
     
     - parameter createWebhookCliSessionRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createWebhookCliSession(createWebhookCliSessionRequest: CreateWebhookCliSessionRequest? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: CreateWebhookCliSession201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createWebhookCliSessionWithRequestBuilder(createWebhookCliSessionRequest: createWebhookCliSessionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create CLI forwarding session
     - POST /v1/webhook-cli/sessions
     - Register a new session for receiving webhook events via SSE.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter createWebhookCliSessionRequest: (body)  (optional)
     - returns: RequestBuilder<CreateWebhookCliSession201Response> 
     */
    open class func createWebhookCliSessionWithRequestBuilder(createWebhookCliSessionRequest: CreateWebhookCliSessionRequest? = nil) -> RequestBuilder<CreateWebhookCliSession201Response> {
        let localVariablePath = "/v1/webhook-cli/sessions"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createWebhookCliSessionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateWebhookCliSession201Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Close CLI session
     
     - parameter sessionId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteWebhookCliSession(sessionId: String, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: DeleteWebhookCliSession200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteWebhookCliSessionWithRequestBuilder(sessionId: sessionId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Close CLI session
     - DELETE /v1/webhook-cli/sessions/{session_id}
     - Close a webhook CLI forwarding session.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter sessionId: (path)  
     - returns: RequestBuilder<DeleteWebhookCliSession200Response> 
     */
    open class func deleteWebhookCliSessionWithRequestBuilder(sessionId: String) -> RequestBuilder<DeleteWebhookCliSession200Response> {
        var localVariablePath = "/v1/webhook-cli/sessions/{session_id}"
        let sessionIdPreEscape = "\(APIHelper.mapValueToPathItem(sessionId))"
        let sessionIdPostEscape = sessionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{session_id}", with: sessionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteWebhookCliSession200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List recent webhook deliveries
     
     - parameter limit: (query) Maximum deliveries to return (optional, default to 50)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listWebhookDeliveries(limit: Int? = nil, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ListWebhookDeliveries200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listWebhookDeliveriesWithRequestBuilder(limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List recent webhook deliveries
     - GET /v1/webhook-cli/deliveries
     - List recent webhook deliveries for replay.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter limit: (query) Maximum deliveries to return (optional, default to 50)
     - returns: RequestBuilder<ListWebhookDeliveries200Response> 
     */
    open class func listWebhookDeliveriesWithRequestBuilder(limit: Int? = nil) -> RequestBuilder<ListWebhookDeliveries200Response> {
        let localVariablePath = "/v1/webhook-cli/deliveries"
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListWebhookDeliveries200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Replay webhook delivery
     
     - parameter deliveryId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func replayWebhookDelivery(deliveryId: Int, apiResponseQueue: DispatchQueue = MailOddsAPI.apiResponseQueue, completion: @escaping ((_ data: ReplayWebhookDelivery200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return replayWebhookDeliveryWithRequestBuilder(deliveryId: deliveryId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Replay webhook delivery
     - POST /v1/webhook-cli/deliveries/{delivery_id}/replay
     - Replay a historical webhook delivery to active CLI sessions.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter deliveryId: (path)  
     - returns: RequestBuilder<ReplayWebhookDelivery200Response> 
     */
    open class func replayWebhookDeliveryWithRequestBuilder(deliveryId: Int) -> RequestBuilder<ReplayWebhookDelivery200Response> {
        var localVariablePath = "/v1/webhook-cli/deliveries/{delivery_id}/replay"
        let deliveryIdPreEscape = "\(APIHelper.mapValueToPathItem(deliveryId))"
        let deliveryIdPostEscape = deliveryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{delivery_id}", with: deliveryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MailOddsAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReplayWebhookDelivery200Response>.Type = MailOddsAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
