//
// AddDmarcDomain201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddDmarcDomain201Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var domain: DmarcDomain?

    public init(schemaVersion: String? = nil, requestId: String? = nil, domain: DmarcDomain? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(domain, forKey: .domain)
    }
}

