//
// AddSuppressionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddSuppressionResponse: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var added: Int?
    public var skipped: Int?

    public init(schemaVersion: String? = nil, added: Int? = nil, skipped: Int? = nil) {
        self.schemaVersion = schemaVersion
        self.added = added
        self.skipped = skipped
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case added
        case skipped
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(added, forKey: .added)
        try container.encodeIfPresent(skipped, forKey: .skipped)
    }
}

