//
// BatchCheckOoo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatchCheckOoo200Response: Sendable, Codable, Hashable {

    public var results: [BatchCheckOoo200ResponseResultsInner]?
    public var total: Int?
    public var oooCount: Int?

    public init(results: [BatchCheckOoo200ResponseResultsInner]? = nil, total: Int? = nil, oooCount: Int? = nil) {
        self.results = results
        self.total = total
        self.oooCount = oooCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case total
        case oooCount = "ooo_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(oooCount, forKey: .oooCount)
    }
}

