//
// BatchDeliverResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatchDeliverResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "queued"
        case allRejected = "all_rejected"
    }
    public var schemaVersion: String?
    /** Unique request identifier */
    public var requestId: String?
    /** Total recipients submitted */
    public var total: Int?
    /** Number of recipients accepted for delivery */
    public var accepted: Int?
    /** Recipients that were rejected (suppressed or failed validation) */
    public var rejected: [BatchDeliverResponseRejectedInner]?
    /** Batch status */
    public var status: Status?
    public var delivery: BatchDeliverResponseDelivery?

    public init(schemaVersion: String? = nil, requestId: String? = nil, total: Int? = nil, accepted: Int? = nil, rejected: [BatchDeliverResponseRejectedInner]? = nil, status: Status? = nil, delivery: BatchDeliverResponseDelivery? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.total = total
        self.accepted = accepted
        self.rejected = rejected
        self.status = status
        self.delivery = delivery
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case total
        case accepted
        case rejected
        case status
        case delivery
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(accepted, forKey: .accepted)
        try container.encodeIfPresent(rejected, forKey: .rejected)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(delivery, forKey: .delivery)
    }
}

