//
// BlacklistMonitor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BlacklistMonitor: Sendable, Codable, Hashable {

    public enum TargetType: String, Sendable, Codable, CaseIterable {
        case ip = "ip"
        case domain = "domain"
    }
    /** Monitor UUID */
    public var id: String?
    /** IP address or domain being monitored */
    public var target: String?
    public var targetType: TargetType?
    /** Current status (clean, listed) */
    public var status: String?
    /** Number of blacklists currently listing this target */
    public var listedCount: Int?
    public var lastCheckedAt: Date?
    public var latestCheck: BlacklistMonitorLatestCheck?
    public var createdAt: Date?

    public init(id: String? = nil, target: String? = nil, targetType: TargetType? = nil, status: String? = nil, listedCount: Int? = nil, lastCheckedAt: Date? = nil, latestCheck: BlacklistMonitorLatestCheck? = nil, createdAt: Date? = nil) {
        self.id = id
        self.target = target
        self.targetType = targetType
        self.status = status
        self.listedCount = listedCount
        self.lastCheckedAt = lastCheckedAt
        self.latestCheck = latestCheck
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case target
        case targetType = "target_type"
        case status
        case listedCount = "listed_count"
        case lastCheckedAt = "last_checked_at"
        case latestCheck = "latest_check"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(target, forKey: .target)
        try container.encodeIfPresent(targetType, forKey: .targetType)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(listedCount, forKey: .listedCount)
        try container.encodeIfPresent(lastCheckedAt, forKey: .lastCheckedAt)
        try container.encodeIfPresent(latestCheck, forKey: .latestCheck)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BlacklistMonitor: Identifiable {}
