//
// CampaignStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Delivery and engagement statistics. Present when the campaign has started sending. */
public struct CampaignStats: Sendable, Codable, Hashable {

    public var sent: Int?
    public var delivered: Int?
    public var opened: Int?
    public var clicked: Int?
    public var bounced: Int?
    public var unsubscribed: Int?
    public var complained: Int?
    public var deliveryRate: Double?
    public var openRate: Double?
    public var clickRate: Double?

    public init(sent: Int? = nil, delivered: Int? = nil, opened: Int? = nil, clicked: Int? = nil, bounced: Int? = nil, unsubscribed: Int? = nil, complained: Int? = nil, deliveryRate: Double? = nil, openRate: Double? = nil, clickRate: Double? = nil) {
        self.sent = sent
        self.delivered = delivered
        self.opened = opened
        self.clicked = clicked
        self.bounced = bounced
        self.unsubscribed = unsubscribed
        self.complained = complained
        self.deliveryRate = deliveryRate
        self.openRate = openRate
        self.clickRate = clickRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sent
        case delivered
        case opened
        case clicked
        case bounced
        case unsubscribed
        case complained
        case deliveryRate = "delivery_rate"
        case openRate = "open_rate"
        case clickRate = "click_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sent, forKey: .sent)
        try container.encodeIfPresent(delivered, forKey: .delivered)
        try container.encodeIfPresent(opened, forKey: .opened)
        try container.encodeIfPresent(clicked, forKey: .clicked)
        try container.encodeIfPresent(bounced, forKey: .bounced)
        try container.encodeIfPresent(unsubscribed, forKey: .unsubscribed)
        try container.encodeIfPresent(complained, forKey: .complained)
        try container.encodeIfPresent(deliveryRate, forKey: .deliveryRate)
        try container.encodeIfPresent(openRate, forKey: .openRate)
        try container.encodeIfPresent(clickRate, forKey: .clickRate)
    }
}

