//
// CreateStoreRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct CreateStoreRequest: Codable, Hashable {

    public enum Platform: String, Codable, CaseIterable {
        case woocommerce = "woocommerce"
        case prestashop = "prestashop"
        case shopify = "shopify"
        case feed = "feed"
        case custom = "custom"
    }
    public enum AuthMethod: String, Codable, CaseIterable {
        case pluginHandshake = "plugin_handshake"
        case apiKey = "api_key"
        case oauth = "oauth"
        case feedUrl = "feed_url"
    }
    /** E-commerce platform */
    public var platform: Platform
    /** Display name for the store */
    public var storeName: String
    /** Store base URL */
    public var storeUrl: String
    /** Authentication method */
    public var authMethod: AuthMethod
    /** Platform-specific settings (e.g., API keys, feed URL) */
    public var settings: AnyCodable?

    public init(platform: Platform, storeName: String, storeUrl: String, authMethod: AuthMethod, settings: AnyCodable? = nil) {
        self.platform = platform
        self.storeName = storeName
        self.storeUrl = storeUrl
        self.authMethod = authMethod
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case storeName = "store_name"
        case storeUrl = "store_url"
        case authMethod = "auth_method"
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(storeName, forKey: .storeName)
        try container.encode(storeUrl, forKey: .storeUrl)
        try container.encode(authMethod, forKey: .authMethod)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

