//
// DeliverResponseDelivery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeliverResponseDelivery: Sendable, Codable, Hashable {

    /** IP pool used */
    public var pool: String?
    /** Delivery lane */
    public var lane: String?
    /** Whether warmup throttling was applied */
    public var warmupLimited: Bool?

    public init(pool: String? = nil, lane: String? = nil, warmupLimited: Bool? = nil) {
        self.pool = pool
        self.lane = lane
        self.warmupLimited = warmupLimited
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pool
        case lane
        case warmupLimited = "warmup_limited"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pool, forKey: .pool)
        try container.encodeIfPresent(lane, forKey: .lane)
        try container.encodeIfPresent(warmupLimited, forKey: .warmupLimited)
    }
}

