//
// DeliverRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeliverRequest: Sendable, Codable, Hashable {

    public enum CampaignType: String, Sendable, Codable, CaseIterable {
        case orderConfirmation = "order_confirmation"
        case shippingNotification = "shipping_notification"
        case subscriptionConfirm = "subscription_confirm"
        case reviewRequest = "review_request"
        case eventInvitation = "event_invitation"
        case promotional = "promotional"
        case welcome = "welcome"
        case passwordReset = "password_reset"
        case appointmentReminder = "appointment_reminder"
        case ticketConfirmation = "ticket_confirmation"
    }
    /** List of recipient email addresses */
    public var to: [DeliverRequestToInner]
    /** Sender email address (must match sending domain) */
    public var from: String
    /** Email subject line */
    public var subject: String
    /** HTML email body */
    public var html: String?
    /** Plain text email body */
    public var text: String?
    /** Sending domain UUID */
    public var domainId: String
    /** Reply-to address */
    public var replyTo: String?
    /** Extra email headers */
    public var headers: JSONValue?
    /** Tags for categorization */
    public var tags: [String]?
    /** Campaign type for JSON-LD auto-generation */
    public var campaignType: CampaignType?
    public var structuredData: DeliverRequestStructuredData?
    public var options: DeliverRequestOptions?

    public init(to: [DeliverRequestToInner], from: String, subject: String, html: String? = nil, text: String? = nil, domainId: String, replyTo: String? = nil, headers: JSONValue? = nil, tags: [String]? = nil, campaignType: CampaignType? = nil, structuredData: DeliverRequestStructuredData? = nil, options: DeliverRequestOptions? = nil) {
        self.to = to
        self.from = from
        self.subject = subject
        self.html = html
        self.text = text
        self.domainId = domainId
        self.replyTo = replyTo
        self.headers = headers
        self.tags = tags
        self.campaignType = campaignType
        self.structuredData = structuredData
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case to
        case from
        case subject
        case html
        case text
        case domainId = "domain_id"
        case replyTo = "reply_to"
        case headers
        case tags
        case campaignType = "campaign_type"
        case structuredData = "structured_data"
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(to, forKey: .to)
        try container.encode(from, forKey: .from)
        try container.encode(subject, forKey: .subject)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encode(domainId, forKey: .domainId)
        try container.encodeIfPresent(replyTo, forKey: .replyTo)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(campaignType, forKey: .campaignType)
        try container.encodeIfPresent(structuredData, forKey: .structuredData)
        try container.encodeIfPresent(options, forKey: .options)
    }
}

