//
// GetBounceRecords200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetBounceRecords200Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    /** Unique request identifier */
    public var requestId: String?
    public var records: [GetBounceRecords200ResponseRecordsInner]?
    public var pagination: Pagination?

    public init(schemaVersion: String? = nil, requestId: String? = nil, records: [GetBounceRecords200ResponseRecordsInner]? = nil, pagination: Pagination? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.records = records
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case records
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(records, forKey: .records)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

