//
// GetBlacklistHistory200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetBlacklistHistory200Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var checks: [GetBlacklistHistory200ResponseChecksInner]?
    public var pagination: Pagination?

    public init(schemaVersion: String? = nil, requestId: String? = nil, checks: [GetBlacklistHistory200ResponseChecksInner]? = nil, pagination: Pagination? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.checks = checks
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case checks
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(checks, forKey: .checks)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

