//
// GetCampaignDeliveryConfidence200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCampaignDeliveryConfidence200Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    /** Unique request identifier */
    public var requestId: String?
    public var campaignId: String?
    /** Predicted delivery confidence (0-100) */
    public var confidenceScore: Int?
    public var factors: GetCampaignDeliveryConfidence200ResponseFactors?
    /** Actionable recommendations to improve delivery confidence */
    public var recommendations: [String]?

    public init(schemaVersion: String? = nil, requestId: String? = nil, campaignId: String? = nil, confidenceScore: Int? = nil, factors: GetCampaignDeliveryConfidence200ResponseFactors? = nil, recommendations: [String]? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.campaignId = campaignId
        self.confidenceScore = confidenceScore
        self.factors = factors
        self.recommendations = recommendations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case campaignId = "campaign_id"
        case confidenceScore = "confidence_score"
        case factors
        case recommendations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(campaignId, forKey: .campaignId)
        try container.encodeIfPresent(confidenceScore, forKey: .confidenceScore)
        try container.encodeIfPresent(factors, forKey: .factors)
        try container.encodeIfPresent(recommendations, forKey: .recommendations)
    }
}

