//
// GetCampaignDeliveryConfidence200ResponseFactorsDomainAuth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCampaignDeliveryConfidence200ResponseFactorsDomainAuth: Sendable, Codable, Hashable {

    public var score: Int?
    public var dkim: Bool?
    public var spf: Bool?
    public var dmarc: Bool?

    public init(score: Int? = nil, dkim: Bool? = nil, spf: Bool? = nil, dmarc: Bool? = nil) {
        self.score = score
        self.dkim = dkim
        self.spf = spf
        self.dmarc = dmarc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case score
        case dkim
        case spf
        case dmarc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(dkim, forKey: .dkim)
        try container.encodeIfPresent(spf, forKey: .spf)
        try container.encodeIfPresent(dmarc, forKey: .dmarc)
    }
}

