//
// GetCampaignAttribution200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCampaignAttribution200Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var campaignId: String?
    public var attribution: GetCampaignAttribution200ResponseAttribution?

    public init(schemaVersion: String? = nil, requestId: String? = nil, campaignId: String? = nil, attribution: GetCampaignAttribution200ResponseAttribution? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.campaignId = campaignId
        self.attribution = attribution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case campaignId = "campaign_id"
        case attribution
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(campaignId, forKey: .campaignId)
        try container.encodeIfPresent(attribution, forKey: .attribution)
    }
}

