//
// GetCampaignDeliveryConfidence200ResponseFactors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetCampaignDeliveryConfidence200ResponseFactors: Sendable, Codable, Hashable {

    public var listQuality: GetCampaignDeliveryConfidence200ResponseFactorsListQuality?
    public var senderReputation: GetCampaignDeliveryConfidence200ResponseFactorsSenderReputation?
    public var domainAuth: GetCampaignDeliveryConfidence200ResponseFactorsDomainAuth?

    public init(listQuality: GetCampaignDeliveryConfidence200ResponseFactorsListQuality? = nil, senderReputation: GetCampaignDeliveryConfidence200ResponseFactorsSenderReputation? = nil, domainAuth: GetCampaignDeliveryConfidence200ResponseFactorsDomainAuth? = nil) {
        self.listQuality = listQuality
        self.senderReputation = senderReputation
        self.domainAuth = domainAuth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case listQuality = "list_quality"
        case senderReputation = "sender_reputation"
        case domainAuth = "domain_auth"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(listQuality, forKey: .listQuality)
        try container.encodeIfPresent(senderReputation, forKey: .senderReputation)
        try container.encodeIfPresent(domainAuth, forKey: .domainAuth)
    }
}

