//
// GetDisengagedContacts200ResponsePagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDisengagedContacts200ResponsePagination: Sendable, Codable, Hashable {

    public var page: Int?
    public var perPage: Int?
    public var total: Int?
    public var totalPages: Int?
    public var hasNext: Bool?

    public init(page: Int? = nil, perPage: Int? = nil, total: Int? = nil, totalPages: Int? = nil, hasNext: Bool? = nil) {
        self.page = page
        self.perPage = perPage
        self.total = total
        self.totalPages = totalPages
        self.hasNext = hasNext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case perPage = "per_page"
        case total
        case totalPages = "total_pages"
        case hasNext = "has_next"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(totalPages, forKey: .totalPages)
        try container.encodeIfPresent(hasNext, forKey: .hasNext)
    }
}

