//
// GetDmarcTrend200ResponseTrendInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDmarcTrend200ResponseTrendInner: Sendable, Codable, Hashable {

    public var date: Date?
    public var pass: Int?
    public var fail: Int?
    public var total: Int?
    public var passRate: Double?

    public init(date: Date? = nil, pass: Int? = nil, fail: Int? = nil, total: Int? = nil, passRate: Double? = nil) {
        self.date = date
        self.pass = pass
        self.fail = fail
        self.total = total
        self.passRate = passRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case pass
        case fail
        case total
        case passRate = "pass_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(pass, forKey: .pass)
        try container.encodeIfPresent(fail, forKey: .fail)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(passRate, forKey: .passRate)
    }
}

