//
// GetInactiveContactsReport200ResponseByListInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetInactiveContactsReport200ResponseByListInner: Sendable, Codable, Hashable {

    public var listId: String?
    public var listName: String?
    public var inactiveCount: Int?
    public var total: Int?

    public init(listId: String? = nil, listName: String? = nil, inactiveCount: Int? = nil, total: Int? = nil) {
        self.listId = listId
        self.listName = listName
        self.inactiveCount = inactiveCount
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case listId = "list_id"
        case listName = "list_name"
        case inactiveCount = "inactive_count"
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(listId, forKey: .listId)
        try container.encodeIfPresent(listName, forKey: .listName)
        try container.encodeIfPresent(inactiveCount, forKey: .inactiveCount)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

