//
// GetSubscribers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSubscribers200Response: Sendable, Codable, Hashable {

    public var subscribers: [Subscriber]?
    public var total: Int?
    public var page: Int?
    public var perPage: Int?
    public var pages: Int?

    public init(subscribers: [Subscriber]? = nil, total: Int? = nil, page: Int? = nil, perPage: Int? = nil, pages: Int? = nil) {
        self.subscribers = subscribers
        self.total = total
        self.page = page
        self.perPage = perPage
        self.pages = pages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subscribers
        case total
        case page
        case perPage = "per_page"
        case pages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subscribers, forKey: .subscribers)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(pages, forKey: .pages)
    }
}

