//
// GetSendingStats200ResponseStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSendingStats200ResponseStats: Sendable, Codable, Hashable {

    public var period: String?
    public var sent: Int?
    public var delivered: Int?
    public var bounced: Int?
    public var deferred: Int?
    public var failed: Int?
    public var openedTotal: Int?
    public var openedUnique: Int?
    public var clickedTotal: Int?
    public var clickedUnique: Int?
    public var unsubscribed: Int?
    public var deliveryRate: Double?
    public var openRate: Double?
    public var clickRate: Double?
    /** Opens from known bots/scanners */
    public var botOpens: Int?
    /** Verified human opens */
    public var humanOpens: Int?
    /** Percentage of opens from bots */
    public var botOpenPct: Double?

    public init(period: String? = nil, sent: Int? = nil, delivered: Int? = nil, bounced: Int? = nil, deferred: Int? = nil, failed: Int? = nil, openedTotal: Int? = nil, openedUnique: Int? = nil, clickedTotal: Int? = nil, clickedUnique: Int? = nil, unsubscribed: Int? = nil, deliveryRate: Double? = nil, openRate: Double? = nil, clickRate: Double? = nil, botOpens: Int? = nil, humanOpens: Int? = nil, botOpenPct: Double? = nil) {
        self.period = period
        self.sent = sent
        self.delivered = delivered
        self.bounced = bounced
        self.deferred = deferred
        self.failed = failed
        self.openedTotal = openedTotal
        self.openedUnique = openedUnique
        self.clickedTotal = clickedTotal
        self.clickedUnique = clickedUnique
        self.unsubscribed = unsubscribed
        self.deliveryRate = deliveryRate
        self.openRate = openRate
        self.clickRate = clickRate
        self.botOpens = botOpens
        self.humanOpens = humanOpens
        self.botOpenPct = botOpenPct
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case period
        case sent
        case delivered
        case bounced
        case deferred
        case failed
        case openedTotal = "opened_total"
        case openedUnique = "opened_unique"
        case clickedTotal = "clicked_total"
        case clickedUnique = "clicked_unique"
        case unsubscribed
        case deliveryRate = "delivery_rate"
        case openRate = "open_rate"
        case clickRate = "click_rate"
        case botOpens = "bot_opens"
        case humanOpens = "human_opens"
        case botOpenPct = "bot_open_pct"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(period, forKey: .period)
        try container.encodeIfPresent(sent, forKey: .sent)
        try container.encodeIfPresent(delivered, forKey: .delivered)
        try container.encodeIfPresent(bounced, forKey: .bounced)
        try container.encodeIfPresent(deferred, forKey: .deferred)
        try container.encodeIfPresent(failed, forKey: .failed)
        try container.encodeIfPresent(openedTotal, forKey: .openedTotal)
        try container.encodeIfPresent(openedUnique, forKey: .openedUnique)
        try container.encodeIfPresent(clickedTotal, forKey: .clickedTotal)
        try container.encodeIfPresent(clickedUnique, forKey: .clickedUnique)
        try container.encodeIfPresent(unsubscribed, forKey: .unsubscribed)
        try container.encodeIfPresent(deliveryRate, forKey: .deliveryRate)
        try container.encodeIfPresent(openRate, forKey: .openRate)
        try container.encodeIfPresent(clickRate, forKey: .clickRate)
        try container.encodeIfPresent(botOpens, forKey: .botOpens)
        try container.encodeIfPresent(humanOpens, forKey: .humanOpens)
        try container.encodeIfPresent(botOpenPct, forKey: .botOpenPct)
    }
}

