//
// JwksResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** JSON Web Key Set (RFC 7517) */
public struct JwksResponse: Codable, Hashable {

    public var keys: [JwksResponseKeysInner]?

    public init(keys: [JwksResponseKeysInner]? = nil) {
        self.keys = keys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(keys, forKey: .keys)
    }
}

