//
// PolicyListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PolicyListResponse: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var policies: [Policy]?
    public var limits: PolicyListResponseLimits?

    public init(schemaVersion: String? = nil, policies: [Policy]? = nil, limits: PolicyListResponseLimits? = nil) {
        self.schemaVersion = schemaVersion
        self.policies = policies
        self.limits = limits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case policies
        case limits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(policies, forKey: .policies)
        try container.encodeIfPresent(limits, forKey: .limits)
    }
}

