//
// PresignedUploadResponseUpload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PresignedUploadResponseUpload: Sendable, Codable, Hashable {

    public var url: String?
    public var fields: JSONValue?
    public var s3Key: String?
    public var expiresIn: Int?

    public init(url: String? = nil, fields: JSONValue? = nil, s3Key: String? = nil, expiresIn: Int? = nil) {
        self.url = url
        self.fields = fields
        self.s3Key = s3Key
        self.expiresIn = expiresIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case fields
        case s3Key = "s3_key"
        case expiresIn = "expires_in"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(fields, forKey: .fields)
        try container.encodeIfPresent(s3Key, forKey: .s3Key)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
    }
}

