//
// QueryContactListRequestFiltersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QueryContactListRequestFiltersInner: Sendable, Codable, Hashable {

    public enum Operator: String, Sendable, Codable, CaseIterable {
        case eq = "eq"
        case neq = "neq"
        case contains = "contains"
        case _in = "in"
    }
    /** Field to filter on */
    public var field: String?
    public var _operator: Operator?
    /** Filter value */
    public var value: JSONValue?

    public init(field: String? = nil, _operator: Operator? = nil, value: JSONValue? = nil) {
        self.field = field
        self._operator = _operator
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case _operator = "operator"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(field, forKey: .field)
        try container.encodeIfPresent(_operator, forKey: ._operator)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

