//
// RemoveSuppression200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RemoveSuppression200Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var removed: Int?

    public init(schemaVersion: String? = nil, removed: Int? = nil) {
        self.schemaVersion = schemaVersion
        self.removed = removed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case removed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(removed, forKey: .removed)
    }
}

