//
// ResultsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResultsResponse: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    /** Unique request identifier */
    public var requestId: String?
    public var job: Job?
    /** Validation results for this page */
    public var data: [ValidationResult]?
    public var pagination: Pagination?

    public init(schemaVersion: String? = nil, requestId: String? = nil, job: Job? = nil, data: [ValidationResult]? = nil, pagination: Pagination? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.job = job
        self.data = data
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case job
        case data
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(job, forKey: .job)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

