//
// RunSpamCheck201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RunSpamCheck201Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var spamCheck: SpamCheck?

    public init(schemaVersion: String? = nil, requestId: String? = nil, spamCheck: SpamCheck? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.spamCheck = spamCheck
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case spamCheck = "spam_check"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(spamCheck, forKey: .spamCheck)
    }
}

