//
// SendingDomainDnsRecordsNs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SendingDomainDnsRecordsNs: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case pending = "pending"
        case verified = "verified"
    }
    /** Record type (NS) */
    public var type: String?
    /** NS record host (mo.yourdomain.com) */
    public var host: String?
    /** NS target servers */
    public var targets: [String]?
    /** Verification status */
    public var status: Status?
    public var verifiedAt: Date?

    public init(type: String? = nil, host: String? = nil, targets: [String]? = nil, status: Status? = nil, verifiedAt: Date? = nil) {
        self.type = type
        self.host = host
        self.targets = targets
        self.status = status
        self.verifiedAt = verifiedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case host
        case targets
        case status
        case verifiedAt = "verified_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(host, forKey: .host)
        try container.encodeIfPresent(targets, forKey: .targets)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(verifiedAt, forKey: .verifiedAt)
    }
}

