//
// SendingDomain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SendingDomain: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case pendingDns = "pending_dns"
        case dnsPartial = "dns_partial"
        case active = "active"
        case suspended = "suspended"
    }
    /** Domain UUID */
    public var id: String?
    /** Domain name */
    public var domain: String?
    /** Domain type (ns_delegated) */
    public var domainType: String?
    /** Domain verification status */
    public var status: Status?
    /** DKIM selector (e.g. mo1) */
    public var dkimSelector: String?
    public var dnsRecords: SendingDomainDnsRecords?
    /** BIMI SVG logo URL */
    public var bimiSvgUrl: String?
    /** BIMI VMC certificate URL */
    public var bimiVmcUrl: String?
    /** Whether BIMI is enabled */
    public var bimiEnabled: Bool?
    /** Reply forwarding address */
    public var forwardRepliesTo: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String? = nil, domain: String? = nil, domainType: String? = nil, status: Status? = nil, dkimSelector: String? = nil, dnsRecords: SendingDomainDnsRecords? = nil, bimiSvgUrl: String? = nil, bimiVmcUrl: String? = nil, bimiEnabled: Bool? = nil, forwardRepliesTo: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.domain = domain
        self.domainType = domainType
        self.status = status
        self.dkimSelector = dkimSelector
        self.dnsRecords = dnsRecords
        self.bimiSvgUrl = bimiSvgUrl
        self.bimiVmcUrl = bimiVmcUrl
        self.bimiEnabled = bimiEnabled
        self.forwardRepliesTo = forwardRepliesTo
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case domain
        case domainType = "domain_type"
        case status
        case dkimSelector = "dkim_selector"
        case dnsRecords = "dns_records"
        case bimiSvgUrl = "bimi_svg_url"
        case bimiVmcUrl = "bimi_vmc_url"
        case bimiEnabled = "bimi_enabled"
        case forwardRepliesTo = "forward_replies_to"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(domainType, forKey: .domainType)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(dkimSelector, forKey: .dkimSelector)
        try container.encodeIfPresent(dnsRecords, forKey: .dnsRecords)
        try container.encodeIfPresent(bimiSvgUrl, forKey: .bimiSvgUrl)
        try container.encodeIfPresent(bimiVmcUrl, forKey: .bimiVmcUrl)
        try container.encodeIfPresent(bimiEnabled, forKey: .bimiEnabled)
        try container.encodeIfPresent(forwardRepliesTo, forKey: .forwardRepliesTo)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SendingDomain: Identifiable {}
