//
// ServerTestMxRecordsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerTestMxRecordsInner: Sendable, Codable, Hashable {

    public var host: String?
    public var priority: Int?
    public var ip: String?

    public init(host: String? = nil, priority: Int? = nil, ip: String? = nil) {
        self.host = host
        self.priority = priority
        self.ip = ip
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case host
        case priority
        case ip
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(host, forKey: .host)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(ip, forKey: .ip)
    }
}

