//
// SubscriberList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SubscriberList: Sendable, Codable, Hashable {

    /** List UUID */
    public var id: String?
    /** Account ID */
    public var accountId: Int?
    /** List name */
    public var name: String?
    /** List description */
    public var description: String?
    /** Redirect URL after confirmation */
    public var confirmationRedirectUrl: String?
    /** Confirmation email subject */
    public var confirmationSubject: String?
    /** Confirmation email sender name */
    public var confirmationFromName: String?
    /** Total subscriber count */
    public var subscriberCount: Int?
    /** Confirmed subscriber count */
    public var confirmedCount: Int?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String? = nil, accountId: Int? = nil, name: String? = nil, description: String? = nil, confirmationRedirectUrl: String? = nil, confirmationSubject: String? = nil, confirmationFromName: String? = nil, subscriberCount: Int? = nil, confirmedCount: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.accountId = accountId
        self.name = name
        self.description = description
        self.confirmationRedirectUrl = confirmationRedirectUrl
        self.confirmationSubject = confirmationSubject
        self.confirmationFromName = confirmationFromName
        self.subscriberCount = subscriberCount
        self.confirmedCount = confirmedCount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case accountId = "account_id"
        case name
        case description
        case confirmationRedirectUrl = "confirmation_redirect_url"
        case confirmationSubject = "confirmation_subject"
        case confirmationFromName = "confirmation_from_name"
        case subscriberCount = "subscriber_count"
        case confirmedCount = "confirmed_count"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(confirmationRedirectUrl, forKey: .confirmationRedirectUrl)
        try container.encodeIfPresent(confirmationSubject, forKey: .confirmationSubject)
        try container.encodeIfPresent(confirmationFromName, forKey: .confirmationFromName)
        try container.encodeIfPresent(subscriberCount, forKey: .subscriberCount)
        try container.encodeIfPresent(confirmedCount, forKey: .confirmedCount)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SubscriberList: Identifiable {}
