//
// SuppressionEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SuppressionEntry: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case email = "email"
        case domain = "domain"
    }
    public var id: Int?
    public var type: ModelType?
    public var value: String?
    public var reason: String?
    public var createdAt: Date?

    public init(id: Int? = nil, type: ModelType? = nil, value: String? = nil, reason: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.type = type
        self.value = value
        self.reason = reason
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case value
        case reason
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SuppressionEntry: Identifiable {}
