//
// SuppressDisengaged200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SuppressDisengaged200Response: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var suppressedCount: Int?
    public var dryRun: Bool?

    public init(schemaVersion: String? = nil, requestId: String? = nil, suppressedCount: Int? = nil, dryRun: Bool? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.suppressedCount = suppressedCount
        self.dryRun = dryRun
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case suppressedCount = "suppressed_count"
        case dryRun = "dry_run"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(suppressedCount, forKey: .suppressedCount)
        try container.encodeIfPresent(dryRun, forKey: .dryRun)
    }
}

