//
// SuppressionListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SuppressionListResponse: Sendable, Codable, Hashable {

    public var schemaVersion: String?
    public var entries: [SuppressionEntry]?
    public var pagination: Pagination?

    public init(schemaVersion: String? = nil, entries: [SuppressionEntry]? = nil, pagination: Pagination? = nil) {
        self.schemaVersion = schemaVersion
        self.entries = entries
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case entries
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(entries, forKey: .entries)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

