//
// UnsubscribeSubscriber200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UnsubscribeSubscriber200Response: Sendable, Codable, Hashable {

    public var subscriber: Subscriber?

    public init(subscriber: Subscriber? = nil) {
        self.subscriber = subscriber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subscriber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subscriber, forKey: .subscriber)
    }
}

