//
// UpdateContactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct UpdateContactRequest: Sendable, Codable, Hashable {

    public var firstName: String?
    public var lastName: String?
    public var customFields: AnyCodable?

    public init(firstName: String? = nil, lastName: String? = nil, customFields: AnyCodable? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

