//
// BatchProductsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchProductsRequest: Codable, JSONEncodable, Hashable {

    public static let productsRule = ArrayRule(minItems: nil, maxItems: 100, uniqueItems: false)
    public var products: [BatchProductsRequestProductsInner]

    public init(products: [BatchProductsRequestProductsInner]) {
        self.products = products
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case products
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(products, forKey: .products)
    }
}

