//
// CreateJobRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Bulk jobs use the account&#39;s default validation policy. To use a specific policy, set it as default via the Policies API. */
public struct CreateJobRequest: Codable, JSONEncodable, Hashable {

    public static let emailsRule = ArrayRule(minItems: nil, maxItems: 100000, uniqueItems: false)
    /** List of emails to validate */
    public var emails: [String]
    /** Remove duplicate emails */
    public var dedup: Bool? = false
    /** Custom metadata for the job */
    public var metadata: AnyCodable?
    /** URL for completion webhook */
    public var webhookUrl: String?
    /** Unique key for idempotent requests */
    public var idempotencyKey: String?

    public init(emails: [String], dedup: Bool? = false, metadata: AnyCodable? = nil, webhookUrl: String? = nil, idempotencyKey: String? = nil) {
        self.emails = emails
        self.dedup = dedup
        self.metadata = metadata
        self.webhookUrl = webhookUrl
        self.idempotencyKey = idempotencyKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emails
        case dedup
        case metadata
        case webhookUrl = "webhook_url"
        case idempotencyKey = "idempotency_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emails, forKey: .emails)
        try container.encodeIfPresent(dedup, forKey: .dedup)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
        try container.encodeIfPresent(idempotencyKey, forKey: .idempotencyKey)
    }
}

