//
// CreateVariantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateVariantRequest: Codable, JSONEncodable, Hashable {

    public static let weightRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    /** Variant name (e.g., \"Variant A\") */
    public var name: String
    /** Email subject line */
    public var subject: String
    /** HTML email body */
    public var html: String?
    /** Plain text email body */
    public var text: String?
    /** Traffic weight percentage (all variant weights must sum to 100) */
    public var weight: Int

    public init(name: String, subject: String, html: String? = nil, text: String? = nil, weight: Int) {
        self.name = name
        self.subject = subject
        self.html = html
        self.text = text
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case subject
        case html
        case text
        case weight
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(subject, forKey: .subject)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encode(weight, forKey: .weight)
    }
}

