//
// CreateBounceAnalysisRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBounceAnalysisRequest: Codable, JSONEncodable, Hashable {

    public enum Period: String, Codable, CaseIterable {
        case _7d = "7d"
        case _30d = "30d"
        case _90d = "90d"
    }
    /** Sending domain UUID to analyze bounces for */
    public var domainId: String
    /** Time period to analyze */
    public var period: Period? = ._30d

    public init(domainId: String, period: Period? = ._30d) {
        self.domainId = domainId
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domainId = "domain_id"
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domainId, forKey: .domainId)
        try container.encodeIfPresent(period, forKey: .period)
    }
}

