//
// DeliverResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliverResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case queued = "queued"
    }
    public var schemaVersion: String?
    /** Unique request identifier */
    public var requestId: String?
    /** Unique message identifier */
    public var messageId: String?
    /** Delivery status */
    public var status: Status?
    public var delivery: DeliverResponseDelivery?
    /** Pre-send validation results (when validate_first is true) */
    public var validation: AnyCodable?
    /** Content scan results */
    public var contentScan: AnyCodable?

    public init(schemaVersion: String? = nil, requestId: String? = nil, messageId: String? = nil, status: Status? = nil, delivery: DeliverResponseDelivery? = nil, validation: AnyCodable? = nil, contentScan: AnyCodable? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.messageId = messageId
        self.status = status
        self.delivery = delivery
        self.validation = validation
        self.contentScan = contentScan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case messageId = "message_id"
        case status
        case delivery
        case validation
        case contentScan = "content_scan"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(messageId, forKey: .messageId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(delivery, forKey: .delivery)
        try container.encodeIfPresent(validation, forKey: .validation)
        try container.encodeIfPresent(contentScan, forKey: .contentScan)
    }
}

