//
// DmarcDomain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DmarcDomain: Codable, JSONEncodable, Hashable {

    /** Domain UUID */
    public var id: String?
    /** Domain name */
    public var domain: String?
    /** DMARC aggregate report receiving address */
    public var reportingAddress: String?
    /** Whether DNS record has been verified */
    public var dnsVerified: Bool?
    public var dnsVerifiedAt: Date?
    public var createdAt: Date?

    public init(id: String? = nil, domain: String? = nil, reportingAddress: String? = nil, dnsVerified: Bool? = nil, dnsVerifiedAt: Date? = nil, createdAt: Date? = nil) {
        self.id = id
        self.domain = domain
        self.reportingAddress = reportingAddress
        self.dnsVerified = dnsVerified
        self.dnsVerifiedAt = dnsVerifiedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case domain
        case reportingAddress = "reporting_address"
        case dnsVerified = "dns_verified"
        case dnsVerifiedAt = "dns_verified_at"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(reportingAddress, forKey: .reportingAddress)
        try container.encodeIfPresent(dnsVerified, forKey: .dnsVerified)
        try container.encodeIfPresent(dnsVerifiedAt, forKey: .dnsVerifiedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DmarcDomain: Identifiable {}
