//
// GetBounceStats200ResponseStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Bounce statistics with time-series data */
public struct GetBounceStats200ResponseStats: Codable, JSONEncodable, Hashable {

    public var period: String?
    public var groupBy: String?
    public var data: [AnyCodable]?

    public init(period: String? = nil, groupBy: String? = nil, data: [AnyCodable]? = nil) {
        self.period = period
        self.groupBy = groupBy
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case period
        case groupBy = "group_by"
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(period, forKey: .period)
        try container.encodeIfPresent(groupBy, forKey: .groupBy)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

