//
// GetComplaintAssessment200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetComplaintAssessment200Response: Codable, JSONEncodable, Hashable {

    public enum RiskLevel: String, Codable, CaseIterable {
        case low = "low"
        case medium = "medium"
        case high = "high"
        case critical = "critical"
    }
    public var schemaVersion: String?
    public var requestId: String?
    public var complaintRate: Double?
    public var riskLevel: RiskLevel?
    public var totalComplaints: Int?
    public var totalSent: Int?

    public init(schemaVersion: String? = nil, requestId: String? = nil, complaintRate: Double? = nil, riskLevel: RiskLevel? = nil, totalComplaints: Int? = nil, totalSent: Int? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.complaintRate = complaintRate
        self.riskLevel = riskLevel
        self.totalComplaints = totalComplaints
        self.totalSent = totalSent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case complaintRate = "complaint_rate"
        case riskLevel = "risk_level"
        case totalComplaints = "total_complaints"
        case totalSent = "total_sent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(complaintRate, forKey: .complaintRate)
        try container.encodeIfPresent(riskLevel, forKey: .riskLevel)
        try container.encodeIfPresent(totalComplaints, forKey: .totalComplaints)
        try container.encodeIfPresent(totalSent, forKey: .totalSent)
    }
}

