//
// GetCampaignAttribution200ResponseAttribution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCampaignAttribution200ResponseAttribution: Codable, JSONEncodable, Hashable {

    public var firstTouch: GetCampaignAttribution200ResponseAttributionFirstTouch?
    public var lastTouch: GetCampaignAttribution200ResponseAttributionFirstTouch?

    public init(firstTouch: GetCampaignAttribution200ResponseAttributionFirstTouch? = nil, lastTouch: GetCampaignAttribution200ResponseAttributionFirstTouch? = nil) {
        self.firstTouch = firstTouch
        self.lastTouch = lastTouch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstTouch = "first_touch"
        case lastTouch = "last_touch"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstTouch, forKey: .firstTouch)
        try container.encodeIfPresent(lastTouch, forKey: .lastTouch)
    }
}

