//
// GetCampaignProviderIntelligence200ResponseProvidersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCampaignProviderIntelligence200ResponseProvidersInner: Codable, JSONEncodable, Hashable {

    /** Provider name (e.g. gmail, outlook, yahoo) */
    public var provider: String?
    public var sent: Int?
    public var delivered: Int?
    public var bounced: Int?
    public var opened: Int?
    public var clicked: Int?
    public var deliveryRate: Double?
    public var openRate: Double?
    public var clickRate: Double?

    public init(provider: String? = nil, sent: Int? = nil, delivered: Int? = nil, bounced: Int? = nil, opened: Int? = nil, clicked: Int? = nil, deliveryRate: Double? = nil, openRate: Double? = nil, clickRate: Double? = nil) {
        self.provider = provider
        self.sent = sent
        self.delivered = delivered
        self.bounced = bounced
        self.opened = opened
        self.clicked = clicked
        self.deliveryRate = deliveryRate
        self.openRate = openRate
        self.clickRate = clickRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case sent
        case delivered
        case bounced
        case opened
        case clicked
        case deliveryRate = "delivery_rate"
        case openRate = "open_rate"
        case clickRate = "click_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(sent, forKey: .sent)
        try container.encodeIfPresent(delivered, forKey: .delivered)
        try container.encodeIfPresent(bounced, forKey: .bounced)
        try container.encodeIfPresent(opened, forKey: .opened)
        try container.encodeIfPresent(clicked, forKey: .clicked)
        try container.encodeIfPresent(deliveryRate, forKey: .deliveryRate)
        try container.encodeIfPresent(openRate, forKey: .openRate)
        try container.encodeIfPresent(clickRate, forKey: .clickRate)
    }
}

