//
// GetCampaignAttribution200ResponseAttributionFirstTouch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCampaignAttribution200ResponseAttributionFirstTouch: Codable, JSONEncodable, Hashable {

    public var conversions: Int?
    public var revenue: Double?

    public init(conversions: Int? = nil, revenue: Double? = nil) {
        self.conversions = conversions
        self.revenue = revenue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conversions
        case revenue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(conversions, forKey: .conversions)
        try container.encodeIfPresent(revenue, forKey: .revenue)
    }
}

