//
// GetCampaignFunnel200ResponseRates.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCampaignFunnel200ResponseRates: Codable, JSONEncodable, Hashable {

    public var deliveryRate: Double?
    public var openRate: Double?
    public var clickRate: Double?
    public var clickToOpenRate: Double?
    public var bounceRate: Double?
    public var unsubscribeRate: Double?
    public var complaintRate: Double?

    public init(deliveryRate: Double? = nil, openRate: Double? = nil, clickRate: Double? = nil, clickToOpenRate: Double? = nil, bounceRate: Double? = nil, unsubscribeRate: Double? = nil, complaintRate: Double? = nil) {
        self.deliveryRate = deliveryRate
        self.openRate = openRate
        self.clickRate = clickRate
        self.clickToOpenRate = clickToOpenRate
        self.bounceRate = bounceRate
        self.unsubscribeRate = unsubscribeRate
        self.complaintRate = complaintRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveryRate = "delivery_rate"
        case openRate = "open_rate"
        case clickRate = "click_rate"
        case clickToOpenRate = "click_to_open_rate"
        case bounceRate = "bounce_rate"
        case unsubscribeRate = "unsubscribe_rate"
        case complaintRate = "complaint_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deliveryRate, forKey: .deliveryRate)
        try container.encodeIfPresent(openRate, forKey: .openRate)
        try container.encodeIfPresent(clickRate, forKey: .clickRate)
        try container.encodeIfPresent(clickToOpenRate, forKey: .clickToOpenRate)
        try container.encodeIfPresent(bounceRate, forKey: .bounceRate)
        try container.encodeIfPresent(unsubscribeRate, forKey: .unsubscribeRate)
        try container.encodeIfPresent(complaintRate, forKey: .complaintRate)
    }
}

