//
// GetDomainInsightsTrends200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDomainInsightsTrends200Response: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var trends: [AnyCodable]?

    public init(schemaVersion: String? = nil, requestId: String? = nil, trends: [AnyCodable]? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.trends = trends
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case trends
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(trends, forKey: .trends)
    }
}

