//
// GetDmarcDomain200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDmarcDomain200Response: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var domain: GetDmarcDomain200ResponseDomain?

    public init(schemaVersion: String? = nil, requestId: String? = nil, domain: GetDmarcDomain200ResponseDomain? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(domain, forKey: .domain)
    }
}

