//
// GetEngagementScore200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetEngagementScore200Response: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var email: String?
    public var score: Double?
    public var lastEngagedAt: Date?

    public init(schemaVersion: String? = nil, requestId: String? = nil, email: String? = nil, score: Double? = nil, lastEngagedAt: Date? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.email = email
        self.score = score
        self.lastEngagedAt = lastEngagedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case email
        case score
        case lastEngagedAt = "last_engaged_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(lastEngagedAt, forKey: .lastEngagedAt)
    }
}

