//
// GetReputationTimeline200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetReputationTimeline200Response: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var timeline: GetReputationTimeline200ResponseTimeline?

    public init(schemaVersion: String? = nil, requestId: String? = nil, timeline: GetReputationTimeline200ResponseTimeline? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.timeline = timeline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case timeline
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(timeline, forKey: .timeline)
    }
}

