//
// GetSenderHealth200ResponseComponents.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetSenderHealth200ResponseComponents: Codable, JSONEncodable, Hashable {

    public var deliveryRate: GetSenderHealth200ResponseComponentsDeliveryRate?
    public var bounceRate: GetSenderHealth200ResponseComponentsDeliveryRate?
    public var complaintRate: GetSenderHealth200ResponseComponentsDeliveryRate?
    public var authentication: GetSenderHealth200ResponseComponentsDeliveryRate?

    public init(deliveryRate: GetSenderHealth200ResponseComponentsDeliveryRate? = nil, bounceRate: GetSenderHealth200ResponseComponentsDeliveryRate? = nil, complaintRate: GetSenderHealth200ResponseComponentsDeliveryRate? = nil, authentication: GetSenderHealth200ResponseComponentsDeliveryRate? = nil) {
        self.deliveryRate = deliveryRate
        self.bounceRate = bounceRate
        self.complaintRate = complaintRate
        self.authentication = authentication
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveryRate = "delivery_rate"
        case bounceRate = "bounce_rate"
        case complaintRate = "complaint_rate"
        case authentication
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deliveryRate, forKey: .deliveryRate)
        try container.encodeIfPresent(bounceRate, forKey: .bounceRate)
        try container.encodeIfPresent(complaintRate, forKey: .complaintRate)
        try container.encodeIfPresent(authentication, forKey: .authentication)
    }
}

