//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelErrorResponse: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    /** Machine-readable error code */
    public var error: String
    /** Human-readable error message */
    public var message: String?

    public init(schemaVersion: String? = nil, error: String, message: String? = nil) {
        self.schemaVersion = schemaVersion
        self.error = error
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case error
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

