//
// OAuthClientRegistration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OAuthClientRegistration: Codable, JSONEncodable, Hashable {

    /** Issued client identifier */
    public var clientId: String
    /** Human-readable client name */
    public var clientName: String
    /** Registered redirect URIs */
    public var redirectUris: [String]
    /** Allowed grant types */
    public var grantTypes: [String]
    /** Allowed response types */
    public var responseTypes: [String]
    /** Token endpoint auth method */
    public var tokenEndpointAuthMethod: String
    /** Allowed scope */
    public var scope: String?
    /** Unix timestamp of client registration */
    public var clientIdIssuedAt: Int
    /** Client secret (only for confidential clients, shown once) */
    public var clientSecret: String?
    /** Secret expiry (0 = never) */
    public var clientSecretExpiresAt: Int?

    public init(clientId: String, clientName: String, redirectUris: [String], grantTypes: [String], responseTypes: [String], tokenEndpointAuthMethod: String, scope: String? = nil, clientIdIssuedAt: Int, clientSecret: String? = nil, clientSecretExpiresAt: Int? = nil) {
        self.clientId = clientId
        self.clientName = clientName
        self.redirectUris = redirectUris
        self.grantTypes = grantTypes
        self.responseTypes = responseTypes
        self.tokenEndpointAuthMethod = tokenEndpointAuthMethod
        self.scope = scope
        self.clientIdIssuedAt = clientIdIssuedAt
        self.clientSecret = clientSecret
        self.clientSecretExpiresAt = clientSecretExpiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case clientName = "client_name"
        case redirectUris = "redirect_uris"
        case grantTypes = "grant_types"
        case responseTypes = "response_types"
        case tokenEndpointAuthMethod = "token_endpoint_auth_method"
        case scope
        case clientIdIssuedAt = "client_id_issued_at"
        case clientSecret = "client_secret"
        case clientSecretExpiresAt = "client_secret_expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(clientName, forKey: .clientName)
        try container.encode(redirectUris, forKey: .redirectUris)
        try container.encode(grantTypes, forKey: .grantTypes)
        try container.encode(responseTypes, forKey: .responseTypes)
        try container.encode(tokenEndpointAuthMethod, forKey: .tokenEndpointAuthMethod)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encode(clientIdIssuedAt, forKey: .clientIdIssuedAt)
        try container.encodeIfPresent(clientSecret, forKey: .clientSecret)
        try container.encodeIfPresent(clientSecretExpiresAt, forKey: .clientSecretExpiresAt)
    }
}

