//
// QueryProducts200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueryProducts200Response: Codable, JSONEncodable, Hashable {

    public var schemaVersion: String?
    public var requestId: String?
    public var products: [StoreProduct]?
    public var total: Int?
    public var page: Int?
    public var perPage: Int?
    public var pages: Int?
    public var facets: ProductFacets?

    public init(schemaVersion: String? = nil, requestId: String? = nil, products: [StoreProduct]? = nil, total: Int? = nil, page: Int? = nil, perPage: Int? = nil, pages: Int? = nil, facets: ProductFacets? = nil) {
        self.schemaVersion = schemaVersion
        self.requestId = requestId
        self.products = products
        self.total = total
        self.page = page
        self.perPage = perPage
        self.pages = pages
        self.facets = facets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion = "schema_version"
        case requestId = "request_id"
        case products
        case total
        case page
        case perPage = "per_page"
        case pages
        case facets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(products, forKey: .products)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(pages, forKey: .pages)
        try container.encodeIfPresent(facets, forKey: .facets)
    }
}

