//
// SpamCheckChecks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Individual check results */
public struct SpamCheckChecks: Codable, JSONEncodable, Hashable {

    public var domainReputation: AnyCodable?
    public var linkSafety: AnyCodable?
    public var subjectAnalysis: AnyCodable?

    public init(domainReputation: AnyCodable? = nil, linkSafety: AnyCodable? = nil, subjectAnalysis: AnyCodable? = nil) {
        self.domainReputation = domainReputation
        self.linkSafety = linkSafety
        self.subjectAnalysis = subjectAnalysis
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domainReputation = "domain_reputation"
        case linkSafety = "link_safety"
        case subjectAnalysis = "subject_analysis"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domainReputation, forKey: .domainReputation)
        try container.encodeIfPresent(linkSafety, forKey: .linkSafety)
        try container.encodeIfPresent(subjectAnalysis, forKey: .subjectAnalysis)
    }
}

