//
// SuppressionAuditResponseEntriesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SuppressionAuditResponseEntriesInner: Codable, JSONEncodable, Hashable {

    public var id: Int?
    /** Audit event type */
    public var eventType: String?
    public var eventCategory: String?
    /** Event-specific details */
    public var details: AnyCodable?
    public var createdAt: Date?

    public init(id: Int? = nil, eventType: String? = nil, eventCategory: String? = nil, details: AnyCodable? = nil, createdAt: Date? = nil) {
        self.id = id
        self.eventType = eventType
        self.eventCategory = eventCategory
        self.details = details
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case eventType = "event_type"
        case eventCategory = "event_category"
        case details
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encodeIfPresent(eventCategory, forKey: .eventCategory)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SuppressionAuditResponseEntriesInner: Identifiable {}
