//
// TelemetrySummaryTotals.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TelemetrySummaryTotals: Codable, JSONEncodable, Hashable {

    /** Total validations in window */
    public var validations: Int?
    /** Credits consumed */
    public var creditsUsed: Int?

    public init(validations: Int? = nil, creditsUsed: Int? = nil) {
        self.validations = validations
        self.creditsUsed = creditsUsed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case validations
        case creditsUsed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(validations, forKey: .validations)
        try container.encodeIfPresent(creditsUsed, forKey: .creditsUsed)
    }
}

