//
// TrackEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrackEventRequest: Codable, JSONEncodable, Hashable {

    public enum EventType: String, Codable, CaseIterable {
        case purchase = "purchase"
        case cartAbandon = "cart_abandon"
        case browse = "browse"
        case wishlist = "wishlist"
        case review = "review"
        case shadowDnsDwell = "shadow_dns_dwell"
        case cssProbe = "css_probe"
        case identityStitch = "identity_stitch"
    }
    /** Type of commerce event */
    public var eventType: EventType
    /** Email address associated with the event */
    public var email: String
    /** Event-specific data (e.g., order_id, value, product_url) */
    public var properties: AnyCodable?
    /** When the event occurred (defaults to now) */
    public var occurredAt: Date?
    /** Unique key to prevent duplicate events (5 min TTL) */
    public var idempotencyKey: String?

    public init(eventType: EventType, email: String, properties: AnyCodable? = nil, occurredAt: Date? = nil, idempotencyKey: String? = nil) {
        self.eventType = eventType
        self.email = email
        self.properties = properties
        self.occurredAt = occurredAt
        self.idempotencyKey = idempotencyKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType = "event_type"
        case email
        case properties
        case occurredAt = "occurred_at"
        case idempotencyKey = "idempotency_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
        try container.encodeIfPresent(idempotencyKey, forKey: .idempotencyKey)
    }
}

