//
// UpdateOooContactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateOooContactRequest: Codable, JSONEncodable, Hashable {

    public static let durationDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    /** Set to false to clear OOO status */
    public var isActive: Bool?
    public var oooType: String? = "out_of_office"
    public var durationDays: Int? = 7

    public init(isActive: Bool? = nil, oooType: String? = "out_of_office", durationDays: Int? = 7) {
        self.isActive = isActive
        self.oooType = oooType
        self.durationDays = durationDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isActive = "is_active"
        case oooType = "ooo_type"
        case durationDays = "duration_days"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(oooType, forKey: .oooType)
        try container.encodeIfPresent(durationDays, forKey: .durationDays)
    }
}

