//
// UpdateReplyForwardingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateReplyForwardingRequest: Codable, JSONEncodable, Hashable {

    /** Email to forward replies to, or null to disable */
    public var forwardRepliesTo: String?

    public init(forwardRepliesTo: String? = nil) {
        self.forwardRepliesTo = forwardRepliesTo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case forwardRepliesTo = "forward_replies_to"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(forwardRepliesTo, forKey: .forwardRepliesTo)
    }
}

